// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    public static class GetLoadtestingAgent
    {
        public static Task<GetLoadtestingAgentResult> InvokeAsync(GetLoadtestingAgentArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetLoadtestingAgentResult>("yandex:index/getLoadtestingAgent:getLoadtestingAgent", args ?? new GetLoadtestingAgentArgs(), options.WithDefaults());

        public static Output<GetLoadtestingAgentResult> Invoke(GetLoadtestingAgentInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetLoadtestingAgentResult>("yandex:index/getLoadtestingAgent:getLoadtestingAgent", args ?? new GetLoadtestingAgentInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetLoadtestingAgentArgs : global::Pulumi.InvokeArgs
    {
        [Input("agentId", required: true)]
        public string AgentId { get; set; } = null!;

        public GetLoadtestingAgentArgs()
        {
        }
        public static new GetLoadtestingAgentArgs Empty => new GetLoadtestingAgentArgs();
    }

    public sealed class GetLoadtestingAgentInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("agentId", required: true)]
        public Input<string> AgentId { get; set; } = null!;

        public GetLoadtestingAgentInvokeArgs()
        {
        }
        public static new GetLoadtestingAgentInvokeArgs Empty => new GetLoadtestingAgentInvokeArgs();
    }


    [OutputType]
    public sealed class GetLoadtestingAgentResult
    {
        public readonly string AgentId;
        public readonly string ComputeInstanceId;
        public readonly ImmutableArray<Outputs.GetLoadtestingAgentComputeInstanceResult> ComputeInstances;
        public readonly string Description;
        public readonly string FolderId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableDictionary<string, string> Labels;
        public readonly string Name;

        [OutputConstructor]
        private GetLoadtestingAgentResult(
            string agentId,

            string computeInstanceId,

            ImmutableArray<Outputs.GetLoadtestingAgentComputeInstanceResult> computeInstances,

            string description,

            string folderId,

            string id,

            ImmutableDictionary<string, string> labels,

            string name)
        {
            AgentId = agentId;
            ComputeInstanceId = computeInstanceId;
            ComputeInstances = computeInstances;
            Description = description;
            FolderId = folderId;
            Id = id;
            Labels = labels;
            Name = name;
        }
    }
}
