// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    public static class GetSwsSecurityProfile
    {
        public static Task<GetSwsSecurityProfileResult> InvokeAsync(GetSwsSecurityProfileArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSwsSecurityProfileResult>("yandex:index/getSwsSecurityProfile:getSwsSecurityProfile", args ?? new GetSwsSecurityProfileArgs(), options.WithDefaults());

        public static Output<GetSwsSecurityProfileResult> Invoke(GetSwsSecurityProfileInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSwsSecurityProfileResult>("yandex:index/getSwsSecurityProfile:getSwsSecurityProfile", args ?? new GetSwsSecurityProfileInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSwsSecurityProfileArgs : global::Pulumi.InvokeArgs
    {
        [Input("cloudId")]
        public string? CloudId { get; set; }

        [Input("folderId")]
        public string? FolderId { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        [Input("securityProfileId")]
        public string? SecurityProfileId { get; set; }

        public GetSwsSecurityProfileArgs()
        {
        }
        public static new GetSwsSecurityProfileArgs Empty => new GetSwsSecurityProfileArgs();
    }

    public sealed class GetSwsSecurityProfileInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("cloudId")]
        public Input<string>? CloudId { get; set; }

        [Input("folderId")]
        public Input<string>? FolderId { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("securityProfileId")]
        public Input<string>? SecurityProfileId { get; set; }

        public GetSwsSecurityProfileInvokeArgs()
        {
        }
        public static new GetSwsSecurityProfileInvokeArgs Empty => new GetSwsSecurityProfileInvokeArgs();
    }


    [OutputType]
    public sealed class GetSwsSecurityProfileResult
    {
        public readonly string CaptchaId;
        public readonly string CloudId;
        public readonly string CreatedAt;
        public readonly string DefaultAction;
        public readonly string Description;
        public readonly string FolderId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableDictionary<string, string> Labels;
        public readonly string Name;
        public readonly string? SecurityProfileId;
        public readonly ImmutableArray<Outputs.GetSwsSecurityProfileSecurityRuleResult> SecurityRules;

        [OutputConstructor]
        private GetSwsSecurityProfileResult(
            string captchaId,

            string cloudId,

            string createdAt,

            string defaultAction,

            string description,

            string folderId,

            string id,

            ImmutableDictionary<string, string> labels,

            string name,

            string? securityProfileId,

            ImmutableArray<Outputs.GetSwsSecurityProfileSecurityRuleResult> securityRules)
        {
            CaptchaId = captchaId;
            CloudId = cloudId;
            CreatedAt = createdAt;
            DefaultAction = defaultAction;
            Description = description;
            FolderId = folderId;
            Id = id;
            Labels = labels;
            Name = name;
            SecurityProfileId = securityProfileId;
            SecurityRules = securityRules;
        }
    }
}
