// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    [YandexResourceType("yandex:index/swsSecurityProfile:SwsSecurityProfile")]
    public partial class SwsSecurityProfile : global::Pulumi.CustomResource
    {
        [Output("captchaId")]
        public Output<string?> CaptchaId { get; private set; } = null!;

        [Output("cloudId")]
        public Output<string> CloudId { get; private set; } = null!;

        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        [Output("defaultAction")]
        public Output<string?> DefaultAction { get; private set; } = null!;

        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        [Output("folderId")]
        public Output<string> FolderId { get; private set; } = null!;

        [Output("labels")]
        public Output<ImmutableDictionary<string, string>?> Labels { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("securityRules")]
        public Output<ImmutableArray<Outputs.SwsSecurityProfileSecurityRule>> SecurityRules { get; private set; } = null!;


        /// <summary>
        /// Create a SwsSecurityProfile resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SwsSecurityProfile(string name, SwsSecurityProfileArgs? args = null, CustomResourceOptions? options = null)
            : base("yandex:index/swsSecurityProfile:SwsSecurityProfile", name, args ?? new SwsSecurityProfileArgs(), MakeResourceOptions(options, ""))
        {
        }

        private SwsSecurityProfile(string name, Input<string> id, SwsSecurityProfileState? state = null, CustomResourceOptions? options = null)
            : base("yandex:index/swsSecurityProfile:SwsSecurityProfile", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/heyzling/pulumi-yandex/releases/",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SwsSecurityProfile resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SwsSecurityProfile Get(string name, Input<string> id, SwsSecurityProfileState? state = null, CustomResourceOptions? options = null)
        {
            return new SwsSecurityProfile(name, id, state, options);
        }
    }

    public sealed class SwsSecurityProfileArgs : global::Pulumi.ResourceArgs
    {
        [Input("captchaId")]
        public Input<string>? CaptchaId { get; set; }

        [Input("cloudId")]
        public Input<string>? CloudId { get; set; }

        [Input("defaultAction")]
        public Input<string>? DefaultAction { get; set; }

        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("folderId")]
        public Input<string>? FolderId { get; set; }

        [Input("labels")]
        private InputMap<string>? _labels;
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("securityRules")]
        private InputList<Inputs.SwsSecurityProfileSecurityRuleArgs>? _securityRules;
        public InputList<Inputs.SwsSecurityProfileSecurityRuleArgs> SecurityRules
        {
            get => _securityRules ?? (_securityRules = new InputList<Inputs.SwsSecurityProfileSecurityRuleArgs>());
            set => _securityRules = value;
        }

        public SwsSecurityProfileArgs()
        {
        }
        public static new SwsSecurityProfileArgs Empty => new SwsSecurityProfileArgs();
    }

    public sealed class SwsSecurityProfileState : global::Pulumi.ResourceArgs
    {
        [Input("captchaId")]
        public Input<string>? CaptchaId { get; set; }

        [Input("cloudId")]
        public Input<string>? CloudId { get; set; }

        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        [Input("defaultAction")]
        public Input<string>? DefaultAction { get; set; }

        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("folderId")]
        public Input<string>? FolderId { get; set; }

        [Input("labels")]
        private InputMap<string>? _labels;
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("securityRules")]
        private InputList<Inputs.SwsSecurityProfileSecurityRuleGetArgs>? _securityRules;
        public InputList<Inputs.SwsSecurityProfileSecurityRuleGetArgs> SecurityRules
        {
            get => _securityRules ?? (_securityRules = new InputList<Inputs.SwsSecurityProfileSecurityRuleGetArgs>());
            set => _securityRules = value;
        }

        public SwsSecurityProfileState()
        {
        }
        public static new SwsSecurityProfileState Empty => new SwsSecurityProfileState();
    }
}
