// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/heyzling/pulumi-yandex.git/sdk/go/yandex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupFunction(ctx *pulumi.Context, args *LookupFunctionArgs, opts ...pulumi.InvokeOption) (*LookupFunctionResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupFunctionResult
	err := ctx.Invoke("yandex:index/getFunction:getFunction", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getFunction.
type LookupFunctionArgs struct {
	Concurrency   *int                      `pulumi:"concurrency"`
	Connectivity  *GetFunctionConnectivity  `pulumi:"connectivity"`
	FolderId      *string                   `pulumi:"folderId"`
	FunctionId    *string                   `pulumi:"functionId"`
	Name          *string                   `pulumi:"name"`
	Secrets       []GetFunctionSecret       `pulumi:"secrets"`
	StorageMounts []GetFunctionStorageMount `pulumi:"storageMounts"`
}

// A collection of values returned by getFunction.
type LookupFunctionResult struct {
	AsyncInvocations []GetFunctionAsyncInvocation `pulumi:"asyncInvocations"`
	Concurrency      int                          `pulumi:"concurrency"`
	Connectivity     *GetFunctionConnectivity     `pulumi:"connectivity"`
	CreatedAt        string                       `pulumi:"createdAt"`
	Description      string                       `pulumi:"description"`
	Entrypoint       string                       `pulumi:"entrypoint"`
	Environment      map[string]string            `pulumi:"environment"`
	ExecutionTimeout string                       `pulumi:"executionTimeout"`
	FolderId         *string                      `pulumi:"folderId"`
	FunctionId       *string                      `pulumi:"functionId"`
	// The provider-assigned unique ID for this managed resource.
	Id               string                    `pulumi:"id"`
	ImageSize        int                       `pulumi:"imageSize"`
	Labels           map[string]string         `pulumi:"labels"`
	LogOptions       []GetFunctionLogOption    `pulumi:"logOptions"`
	Memory           int                       `pulumi:"memory"`
	Name             *string                   `pulumi:"name"`
	Runtime          string                    `pulumi:"runtime"`
	Secrets          []GetFunctionSecret       `pulumi:"secrets"`
	ServiceAccountId string                    `pulumi:"serviceAccountId"`
	StorageMounts    []GetFunctionStorageMount `pulumi:"storageMounts"`
	Tags             []string                  `pulumi:"tags"`
	TmpfsSize        int                       `pulumi:"tmpfsSize"`
	Version          string                    `pulumi:"version"`
}

func LookupFunctionOutput(ctx *pulumi.Context, args LookupFunctionOutputArgs, opts ...pulumi.InvokeOption) LookupFunctionResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupFunctionResult, error) {
			args := v.(LookupFunctionArgs)
			r, err := LookupFunction(ctx, &args, opts...)
			var s LookupFunctionResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupFunctionResultOutput)
}

// A collection of arguments for invoking getFunction.
type LookupFunctionOutputArgs struct {
	Concurrency   pulumi.IntPtrInput                `pulumi:"concurrency"`
	Connectivity  GetFunctionConnectivityPtrInput   `pulumi:"connectivity"`
	FolderId      pulumi.StringPtrInput             `pulumi:"folderId"`
	FunctionId    pulumi.StringPtrInput             `pulumi:"functionId"`
	Name          pulumi.StringPtrInput             `pulumi:"name"`
	Secrets       GetFunctionSecretArrayInput       `pulumi:"secrets"`
	StorageMounts GetFunctionStorageMountArrayInput `pulumi:"storageMounts"`
}

func (LookupFunctionOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFunctionArgs)(nil)).Elem()
}

// A collection of values returned by getFunction.
type LookupFunctionResultOutput struct{ *pulumi.OutputState }

func (LookupFunctionResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFunctionResult)(nil)).Elem()
}

func (o LookupFunctionResultOutput) ToLookupFunctionResultOutput() LookupFunctionResultOutput {
	return o
}

func (o LookupFunctionResultOutput) ToLookupFunctionResultOutputWithContext(ctx context.Context) LookupFunctionResultOutput {
	return o
}

func (o LookupFunctionResultOutput) AsyncInvocations() GetFunctionAsyncInvocationArrayOutput {
	return o.ApplyT(func(v LookupFunctionResult) []GetFunctionAsyncInvocation { return v.AsyncInvocations }).(GetFunctionAsyncInvocationArrayOutput)
}

func (o LookupFunctionResultOutput) Concurrency() pulumi.IntOutput {
	return o.ApplyT(func(v LookupFunctionResult) int { return v.Concurrency }).(pulumi.IntOutput)
}

func (o LookupFunctionResultOutput) Connectivity() GetFunctionConnectivityPtrOutput {
	return o.ApplyT(func(v LookupFunctionResult) *GetFunctionConnectivity { return v.Connectivity }).(GetFunctionConnectivityPtrOutput)
}

func (o LookupFunctionResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFunctionResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

func (o LookupFunctionResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFunctionResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupFunctionResultOutput) Entrypoint() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFunctionResult) string { return v.Entrypoint }).(pulumi.StringOutput)
}

func (o LookupFunctionResultOutput) Environment() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupFunctionResult) map[string]string { return v.Environment }).(pulumi.StringMapOutput)
}

func (o LookupFunctionResultOutput) ExecutionTimeout() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFunctionResult) string { return v.ExecutionTimeout }).(pulumi.StringOutput)
}

func (o LookupFunctionResultOutput) FolderId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupFunctionResult) *string { return v.FolderId }).(pulumi.StringPtrOutput)
}

func (o LookupFunctionResultOutput) FunctionId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupFunctionResult) *string { return v.FunctionId }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupFunctionResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFunctionResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupFunctionResultOutput) ImageSize() pulumi.IntOutput {
	return o.ApplyT(func(v LookupFunctionResult) int { return v.ImageSize }).(pulumi.IntOutput)
}

func (o LookupFunctionResultOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupFunctionResult) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

func (o LookupFunctionResultOutput) LogOptions() GetFunctionLogOptionArrayOutput {
	return o.ApplyT(func(v LookupFunctionResult) []GetFunctionLogOption { return v.LogOptions }).(GetFunctionLogOptionArrayOutput)
}

func (o LookupFunctionResultOutput) Memory() pulumi.IntOutput {
	return o.ApplyT(func(v LookupFunctionResult) int { return v.Memory }).(pulumi.IntOutput)
}

func (o LookupFunctionResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupFunctionResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func (o LookupFunctionResultOutput) Runtime() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFunctionResult) string { return v.Runtime }).(pulumi.StringOutput)
}

func (o LookupFunctionResultOutput) Secrets() GetFunctionSecretArrayOutput {
	return o.ApplyT(func(v LookupFunctionResult) []GetFunctionSecret { return v.Secrets }).(GetFunctionSecretArrayOutput)
}

func (o LookupFunctionResultOutput) ServiceAccountId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFunctionResult) string { return v.ServiceAccountId }).(pulumi.StringOutput)
}

func (o LookupFunctionResultOutput) StorageMounts() GetFunctionStorageMountArrayOutput {
	return o.ApplyT(func(v LookupFunctionResult) []GetFunctionStorageMount { return v.StorageMounts }).(GetFunctionStorageMountArrayOutput)
}

func (o LookupFunctionResultOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupFunctionResult) []string { return v.Tags }).(pulumi.StringArrayOutput)
}

func (o LookupFunctionResultOutput) TmpfsSize() pulumi.IntOutput {
	return o.ApplyT(func(v LookupFunctionResult) int { return v.TmpfsSize }).(pulumi.IntOutput)
}

func (o LookupFunctionResultOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFunctionResult) string { return v.Version }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupFunctionResultOutput{})
}
