// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/heyzling/pulumi-yandex.git/sdk/go/yandex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupSwsSecurityProfile(ctx *pulumi.Context, args *LookupSwsSecurityProfileArgs, opts ...pulumi.InvokeOption) (*LookupSwsSecurityProfileResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSwsSecurityProfileResult
	err := ctx.Invoke("yandex:index/getSwsSecurityProfile:getSwsSecurityProfile", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSwsSecurityProfile.
type LookupSwsSecurityProfileArgs struct {
	CloudId           *string `pulumi:"cloudId"`
	FolderId          *string `pulumi:"folderId"`
	Name              *string `pulumi:"name"`
	SecurityProfileId *string `pulumi:"securityProfileId"`
}

// A collection of values returned by getSwsSecurityProfile.
type LookupSwsSecurityProfileResult struct {
	CaptchaId     string `pulumi:"captchaId"`
	CloudId       string `pulumi:"cloudId"`
	CreatedAt     string `pulumi:"createdAt"`
	DefaultAction string `pulumi:"defaultAction"`
	Description   string `pulumi:"description"`
	FolderId      string `pulumi:"folderId"`
	// The provider-assigned unique ID for this managed resource.
	Id                string                              `pulumi:"id"`
	Labels            map[string]string                   `pulumi:"labels"`
	Name              string                              `pulumi:"name"`
	SecurityProfileId *string                             `pulumi:"securityProfileId"`
	SecurityRules     []GetSwsSecurityProfileSecurityRule `pulumi:"securityRules"`
}

func LookupSwsSecurityProfileOutput(ctx *pulumi.Context, args LookupSwsSecurityProfileOutputArgs, opts ...pulumi.InvokeOption) LookupSwsSecurityProfileResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupSwsSecurityProfileResult, error) {
			args := v.(LookupSwsSecurityProfileArgs)
			r, err := LookupSwsSecurityProfile(ctx, &args, opts...)
			var s LookupSwsSecurityProfileResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupSwsSecurityProfileResultOutput)
}

// A collection of arguments for invoking getSwsSecurityProfile.
type LookupSwsSecurityProfileOutputArgs struct {
	CloudId           pulumi.StringPtrInput `pulumi:"cloudId"`
	FolderId          pulumi.StringPtrInput `pulumi:"folderId"`
	Name              pulumi.StringPtrInput `pulumi:"name"`
	SecurityProfileId pulumi.StringPtrInput `pulumi:"securityProfileId"`
}

func (LookupSwsSecurityProfileOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSwsSecurityProfileArgs)(nil)).Elem()
}

// A collection of values returned by getSwsSecurityProfile.
type LookupSwsSecurityProfileResultOutput struct{ *pulumi.OutputState }

func (LookupSwsSecurityProfileResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSwsSecurityProfileResult)(nil)).Elem()
}

func (o LookupSwsSecurityProfileResultOutput) ToLookupSwsSecurityProfileResultOutput() LookupSwsSecurityProfileResultOutput {
	return o
}

func (o LookupSwsSecurityProfileResultOutput) ToLookupSwsSecurityProfileResultOutputWithContext(ctx context.Context) LookupSwsSecurityProfileResultOutput {
	return o
}

func (o LookupSwsSecurityProfileResultOutput) CaptchaId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSwsSecurityProfileResult) string { return v.CaptchaId }).(pulumi.StringOutput)
}

func (o LookupSwsSecurityProfileResultOutput) CloudId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSwsSecurityProfileResult) string { return v.CloudId }).(pulumi.StringOutput)
}

func (o LookupSwsSecurityProfileResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSwsSecurityProfileResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

func (o LookupSwsSecurityProfileResultOutput) DefaultAction() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSwsSecurityProfileResult) string { return v.DefaultAction }).(pulumi.StringOutput)
}

func (o LookupSwsSecurityProfileResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSwsSecurityProfileResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupSwsSecurityProfileResultOutput) FolderId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSwsSecurityProfileResult) string { return v.FolderId }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupSwsSecurityProfileResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSwsSecurityProfileResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupSwsSecurityProfileResultOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupSwsSecurityProfileResult) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

func (o LookupSwsSecurityProfileResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSwsSecurityProfileResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupSwsSecurityProfileResultOutput) SecurityProfileId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupSwsSecurityProfileResult) *string { return v.SecurityProfileId }).(pulumi.StringPtrOutput)
}

func (o LookupSwsSecurityProfileResultOutput) SecurityRules() GetSwsSecurityProfileSecurityRuleArrayOutput {
	return o.ApplyT(func(v LookupSwsSecurityProfileResult) []GetSwsSecurityProfileSecurityRule { return v.SecurityRules }).(GetSwsSecurityProfileSecurityRuleArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSwsSecurityProfileResultOutput{})
}
