// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class DatatransferTransferTransformationTransformerFilterColumnsColumns
    {
        /// <summary>
        /// List of columns that will be excluded to transfer.
        /// </summary>
        public readonly ImmutableArray<string> ExcludeColumns;
        /// <summary>
        /// List of columns that will be included to transfer.
        /// </summary>
        public readonly ImmutableArray<string> IncludeColumns;

        [OutputConstructor]
        private DatatransferTransferTransformationTransformerFilterColumnsColumns(
            ImmutableArray<string> excludeColumns,

            ImmutableArray<string> includeColumns)
        {
            ExcludeColumns = excludeColumns;
            IncludeColumns = includeColumns;
        }
    }
}
