// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class DatatransferEndpointSettingsPostgresTarget
    {
        /// <summary>
        /// How to clean collections when activating the transfer. One of "CLICKHOUSE_CLEANUP_POLICY_DISABLED" or "CLICKHOUSE_CLEANUP_POLICY_DROP".
        /// </summary>
        public readonly string? CleanupPolicy;
        /// <summary>
        /// Connection settings. The structure is documented below.
        /// </summary>
        public readonly Outputs.DatatransferEndpointSettingsPostgresTargetConnection? Connection;
        /// <summary>
        /// Name of the database to transfer.
        /// </summary>
        public readonly string? Database;
        /// <summary>
        /// Password for the database access. This is a block with a single field named `raw` which should contain the password.
        /// </summary>
        public readonly Outputs.DatatransferEndpointSettingsPostgresTargetPassword? Password;
        /// <summary>
        /// List of security groups that the transfer associated with this endpoint should use.
        /// </summary>
        public readonly ImmutableArray<string> SecurityGroups;
        /// <summary>
        /// User for the database access.
        /// </summary>
        public readonly string? User;

        [OutputConstructor]
        private DatatransferEndpointSettingsPostgresTarget(
            string? cleanupPolicy,

            Outputs.DatatransferEndpointSettingsPostgresTargetConnection? connection,

            string? database,

            Outputs.DatatransferEndpointSettingsPostgresTargetPassword? password,

            ImmutableArray<string> securityGroups,

            string? user)
        {
            CleanupPolicy = cleanupPolicy;
            Connection = connection;
            Database = database;
            Password = password;
            SecurityGroups = securityGroups;
            User = user;
        }
    }
}
