// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class DatatransferEndpointSettingsClickhouseTargetShardingCustomMappingMapping
    {
        /// <summary>
        /// The value of the column. Currently only the string columns are supported. The structure is documented below.
        /// </summary>
        public readonly Outputs.DatatransferEndpointSettingsClickhouseTargetShardingCustomMappingMappingColumnValue? ColumnValue;
        /// <summary>
        /// The name of the shard into which all the rows with the specified `column_value` will be written.
        /// </summary>
        public readonly string? ShardName;

        [OutputConstructor]
        private DatatransferEndpointSettingsClickhouseTargetShardingCustomMappingMapping(
            Outputs.DatatransferEndpointSettingsClickhouseTargetShardingCustomMappingMappingColumnValue? columnValue,

            string? shardName)
        {
            ColumnValue = columnValue;
            ShardName = shardName;
        }
    }
}
