// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class DatatransferEndpointSettingsClickhouseTargetShardingCustomMapping
    {
        /// <summary>
        /// The name of the column to inspect when deciding the shard to chose for an incoming row.
        /// </summary>
        public readonly string? ColumnName;
        /// <summary>
        /// The mapping of the specified column values to the shard names. The structure is documented below.
        /// </summary>
        public readonly ImmutableArray<Outputs.DatatransferEndpointSettingsClickhouseTargetShardingCustomMappingMapping> Mappings;

        [OutputConstructor]
        private DatatransferEndpointSettingsClickhouseTargetShardingCustomMapping(
            string? columnName,

            ImmutableArray<Outputs.DatatransferEndpointSettingsClickhouseTargetShardingCustomMappingMapping> mappings)
        {
            ColumnName = columnName;
            Mappings = mappings;
        }
    }
}
