// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetKubernetesClusterMasterResult
    {
        public readonly string ClusterCaCertificate;
        public readonly int EtcdClusterSize;
        public readonly string ExternalV4Address;
        public readonly string ExternalV4Endpoint;
        public readonly string ExternalV6Address;
        public readonly string ExternalV6Endpoint;
        public readonly string InternalV4Address;
        public readonly string InternalV4Endpoint;
        public readonly ImmutableArray<Outputs.GetKubernetesClusterMasterMaintenancePolicyResult> MaintenancePolicies;
        public readonly ImmutableArray<Outputs.GetKubernetesClusterMasterMasterLocationResult> MasterLocations;
        public readonly ImmutableArray<Outputs.GetKubernetesClusterMasterMasterLoggingResult> MasterLoggings;
        public readonly bool PublicIp;
        public readonly ImmutableArray<Outputs.GetKubernetesClusterMasterRegionalResult> Regionals;
        public readonly ImmutableArray<string> SecurityGroupIds;
        public readonly string Version;
        public readonly ImmutableArray<Outputs.GetKubernetesClusterMasterVersionInfoResult> VersionInfos;
        public readonly ImmutableArray<Outputs.GetKubernetesClusterMasterZonalResult> Zonals;

        [OutputConstructor]
        private GetKubernetesClusterMasterResult(
            string clusterCaCertificate,

            int etcdClusterSize,

            string externalV4Address,

            string externalV4Endpoint,

            string externalV6Address,

            string externalV6Endpoint,

            string internalV4Address,

            string internalV4Endpoint,

            ImmutableArray<Outputs.GetKubernetesClusterMasterMaintenancePolicyResult> maintenancePolicies,

            ImmutableArray<Outputs.GetKubernetesClusterMasterMasterLocationResult> masterLocations,

            ImmutableArray<Outputs.GetKubernetesClusterMasterMasterLoggingResult> masterLoggings,

            bool publicIp,

            ImmutableArray<Outputs.GetKubernetesClusterMasterRegionalResult> regionals,

            ImmutableArray<string> securityGroupIds,

            string version,

            ImmutableArray<Outputs.GetKubernetesClusterMasterVersionInfoResult> versionInfos,

            ImmutableArray<Outputs.GetKubernetesClusterMasterZonalResult> zonals)
        {
            ClusterCaCertificate = clusterCaCertificate;
            EtcdClusterSize = etcdClusterSize;
            ExternalV4Address = externalV4Address;
            ExternalV4Endpoint = externalV4Endpoint;
            ExternalV6Address = externalV6Address;
            ExternalV6Endpoint = externalV6Endpoint;
            InternalV4Address = internalV4Address;
            InternalV4Endpoint = internalV4Endpoint;
            MaintenancePolicies = maintenancePolicies;
            MasterLocations = masterLocations;
            MasterLoggings = masterLoggings;
            PublicIp = publicIp;
            Regionals = regionals;
            SecurityGroupIds = securityGroupIds;
            Version = version;
            VersionInfos = versionInfos;
            Zonals = zonals;
        }
    }
}
