// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetMdbKafkaConnectorConnectorConfigMirrormakerResult
    {
        public readonly int ReplicationFactor;
        public readonly ImmutableArray<Outputs.GetMdbKafkaConnectorConnectorConfigMirrormakerSourceClusterResult> SourceClusters;
        public readonly ImmutableArray<Outputs.GetMdbKafkaConnectorConnectorConfigMirrormakerTargetClusterResult> TargetClusters;
        public readonly string Topics;

        [OutputConstructor]
        private GetMdbKafkaConnectorConnectorConfigMirrormakerResult(
            int replicationFactor,

            ImmutableArray<Outputs.GetMdbKafkaConnectorConnectorConfigMirrormakerSourceClusterResult> sourceClusters,

            ImmutableArray<Outputs.GetMdbKafkaConnectorConnectorConfigMirrormakerTargetClusterResult> targetClusters,

            string topics)
        {
            ReplicationFactor = replicationFactor;
            SourceClusters = sourceClusters;
            TargetClusters = targetClusters;
            Topics = topics;
        }
    }
}
