// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetMdbMongodbClusterClusterConfigMongodResult
    {
        public readonly Outputs.GetMdbMongodbClusterClusterConfigMongodAuditLogResult AuditLog;
        public readonly Outputs.GetMdbMongodbClusterClusterConfigMongodNetResult? Net;
        public readonly Outputs.GetMdbMongodbClusterClusterConfigMongodOperationProfilingResult? OperationProfiling;
        public readonly Outputs.GetMdbMongodbClusterClusterConfigMongodSecurityResult Security;
        public readonly Outputs.GetMdbMongodbClusterClusterConfigMongodSetParameterResult SetParameter;
        public readonly Outputs.GetMdbMongodbClusterClusterConfigMongodStorageResult? Storage;

        [OutputConstructor]
        private GetMdbMongodbClusterClusterConfigMongodResult(
            Outputs.GetMdbMongodbClusterClusterConfigMongodAuditLogResult auditLog,

            Outputs.GetMdbMongodbClusterClusterConfigMongodNetResult? net,

            Outputs.GetMdbMongodbClusterClusterConfigMongodOperationProfilingResult? operationProfiling,

            Outputs.GetMdbMongodbClusterClusterConfigMongodSecurityResult security,

            Outputs.GetMdbMongodbClusterClusterConfigMongodSetParameterResult setParameter,

            Outputs.GetMdbMongodbClusterClusterConfigMongodStorageResult? storage)
        {
            AuditLog = auditLog;
            Net = net;
            OperationProfiling = operationProfiling;
            Security = security;
            SetParameter = setParameter;
            Storage = storage;
        }
    }
}
