// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetServerlessContainerLogOptionResult
    {
        public readonly bool Disabled;
        public readonly string FolderId;
        public readonly string LogGroupId;
        public readonly string MinLevel;

        [OutputConstructor]
        private GetServerlessContainerLogOptionResult(
            bool disabled,

            string folderId,

            string logGroupId,

            string minLevel)
        {
            Disabled = disabled;
            FolderId = folderId;
            LogGroupId = logGroupId;
            MinLevel = minLevel;
        }
    }
}
