// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetSwsSecurityProfileSecurityRuleResult
    {
        public readonly string Description;
        public readonly bool DryRun;
        public readonly string Name;
        public readonly int Priority;
        public readonly ImmutableArray<Outputs.GetSwsSecurityProfileSecurityRuleRuleConditionResult> RuleConditions;
        public readonly ImmutableArray<Outputs.GetSwsSecurityProfileSecurityRuleSmartProtectionResult> SmartProtections;

        [OutputConstructor]
        private GetSwsSecurityProfileSecurityRuleResult(
            string description,

            bool dryRun,

            string name,

            int priority,

            ImmutableArray<Outputs.GetSwsSecurityProfileSecurityRuleRuleConditionResult> ruleConditions,

            ImmutableArray<Outputs.GetSwsSecurityProfileSecurityRuleSmartProtectionResult> smartProtections)
        {
            Description = description;
            DryRun = dryRun;
            Name = name;
            Priority = priority;
            RuleConditions = ruleConditions;
            SmartProtections = smartProtections;
        }
    }
}
