// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetSwsSecurityProfileSecurityRuleSmartProtectionConditionResult
    {
        public readonly ImmutableArray<Outputs.GetSwsSecurityProfileSecurityRuleSmartProtectionConditionAuthorityResult> Authorities;
        public readonly ImmutableArray<Outputs.GetSwsSecurityProfileSecurityRuleSmartProtectionConditionHeaderResult> Headers;
        public readonly ImmutableArray<Outputs.GetSwsSecurityProfileSecurityRuleSmartProtectionConditionHttpMethodResult> HttpMethods;
        public readonly ImmutableArray<Outputs.GetSwsSecurityProfileSecurityRuleSmartProtectionConditionRequestUriResult> RequestUris;
        public readonly ImmutableArray<Outputs.GetSwsSecurityProfileSecurityRuleSmartProtectionConditionSourceIpResult> SourceIps;

        [OutputConstructor]
        private GetSwsSecurityProfileSecurityRuleSmartProtectionConditionResult(
            ImmutableArray<Outputs.GetSwsSecurityProfileSecurityRuleSmartProtectionConditionAuthorityResult> authorities,

            ImmutableArray<Outputs.GetSwsSecurityProfileSecurityRuleSmartProtectionConditionHeaderResult> headers,

            ImmutableArray<Outputs.GetSwsSecurityProfileSecurityRuleSmartProtectionConditionHttpMethodResult> httpMethods,

            ImmutableArray<Outputs.GetSwsSecurityProfileSecurityRuleSmartProtectionConditionRequestUriResult> requestUris,

            ImmutableArray<Outputs.GetSwsSecurityProfileSecurityRuleSmartProtectionConditionSourceIpResult> sourceIps)
        {
            Authorities = authorities;
            Headers = headers;
            HttpMethods = httpMethods;
            RequestUris = requestUris;
            SourceIps = sourceIps;
        }
    }
}
