// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetSwsSecurityProfileSecurityRuleSmartProtectionConditionSourceIpResult
    {
        public readonly ImmutableArray<Outputs.GetSwsSecurityProfileSecurityRuleSmartProtectionConditionSourceIpGeoIpMatchResult> GeoIpMatches;
        public readonly ImmutableArray<Outputs.GetSwsSecurityProfileSecurityRuleSmartProtectionConditionSourceIpGeoIpNotMatchResult> GeoIpNotMatches;
        public readonly ImmutableArray<Outputs.GetSwsSecurityProfileSecurityRuleSmartProtectionConditionSourceIpIpRangesMatchResult> IpRangesMatches;
        public readonly ImmutableArray<Outputs.GetSwsSecurityProfileSecurityRuleSmartProtectionConditionSourceIpIpRangesNotMatchResult> IpRangesNotMatches;

        [OutputConstructor]
        private GetSwsSecurityProfileSecurityRuleSmartProtectionConditionSourceIpResult(
            ImmutableArray<Outputs.GetSwsSecurityProfileSecurityRuleSmartProtectionConditionSourceIpGeoIpMatchResult> geoIpMatches,

            ImmutableArray<Outputs.GetSwsSecurityProfileSecurityRuleSmartProtectionConditionSourceIpGeoIpNotMatchResult> geoIpNotMatches,

            ImmutableArray<Outputs.GetSwsSecurityProfileSecurityRuleSmartProtectionConditionSourceIpIpRangesMatchResult> ipRangesMatches,

            ImmutableArray<Outputs.GetSwsSecurityProfileSecurityRuleSmartProtectionConditionSourceIpIpRangesNotMatchResult> ipRangesNotMatches)
        {
            GeoIpMatches = geoIpMatches;
            GeoIpNotMatches = geoIpNotMatches;
            IpRangesMatches = ipRangesMatches;
            IpRangesNotMatches = ipRangesNotMatches;
        }
    }
}
