// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class IamServiceAccountApiKeyOutputToLockbox
    {
        /// <summary>
        /// Entry where to store the value of `secret_key`.
        /// </summary>
        public readonly string EntryForSecretKey;
        /// <summary>
        /// ID of the Lockbox secret where to store the sensible values.
        /// </summary>
        public readonly string SecretId;

        [OutputConstructor]
        private IamServiceAccountApiKeyOutputToLockbox(
            string entryForSecretKey,

            string secretId)
        {
            EntryForSecretKey = entryForSecretKey;
            SecretId = secretId;
        }
    }
}
