// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class LoadtestingAgentComputeInstanceNetworkInterface
    {
        public readonly int? Index;
        /// <summary>
        /// Manual set static IP address.
        /// </summary>
        public readonly string? IpAddress;
        /// <summary>
        /// Flag for allocating IPv4 address for the network interface.
        /// </summary>
        public readonly bool? Ipv4;
        /// <summary>
        /// Flag for allocating IPv6 address for the network interface.
        /// </summary>
        public readonly bool? Ipv6;
        /// <summary>
        /// Manual set static IPv6 address.
        /// </summary>
        public readonly string? Ipv6Address;
        public readonly string? MacAddress;
        /// <summary>
        /// Flag for using NAT.
        /// </summary>
        public readonly bool? Nat;
        /// <summary>
        /// A public address that can be used to access the internet over NAT.
        /// </summary>
        public readonly string? NatIpAddress;
        public readonly string? NatIpVersion;
        /// <summary>
        /// Security group ids for network interface.
        /// </summary>
        public readonly ImmutableArray<string> SecurityGroupIds;
        /// <summary>
        /// The ID of the subnet to attach this interface to. The subnet must reside in the same zone where this instance was created.
        /// </summary>
        public readonly string SubnetId;

        [OutputConstructor]
        private LoadtestingAgentComputeInstanceNetworkInterface(
            int? index,

            string? ipAddress,

            bool? ipv4,

            bool? ipv6,

            string? ipv6Address,

            string? macAddress,

            bool? nat,

            string? natIpAddress,

            string? natIpVersion,

            ImmutableArray<string> securityGroupIds,

            string subnetId)
        {
            Index = index;
            IpAddress = ipAddress;
            Ipv4 = ipv4;
            Ipv6 = ipv6;
            Ipv6Address = ipv6Address;
            MacAddress = macAddress;
            Nat = nat;
            NatIpAddress = natIpAddress;
            NatIpVersion = natIpVersion;
            SecurityGroupIds = securityGroupIds;
            SubnetId = subnetId;
        }
    }
}
