// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class MdbMongodbClusterClusterConfigMongodSetParameter
    {
        /// <summary>
        /// Enables the auditing of authorization successes. Can be either true or false.
        /// For more information, see the [auditAuthorizationSuccess](https://www.mongodb.com/docs/manual/reference/parameters/#mongodb-parameter-param.auditAuthorizationSuccess)
        /// description in the official documentation. Available only in enterprise edition.
        /// </summary>
        public readonly bool? AuditAuthorizationSuccess;
        /// <summary>
        /// Enables the flow control. Can be either true or false.
        /// For more information, see the [enableFlowControl](https://www.mongodb.com/docs/rapid/reference/parameters/#mongodb-parameter-param.enableFlowControl)
        /// description in the official documentation.
        /// </summary>
        public readonly bool? EnableFlowControl;
        /// <summary>
        /// The minimum time window in seconds for which the storage engine keeps the snapshot history.
        /// For more information, see the [minSnapshotHistoryWindowInSeconds](https://www.mongodb.com/docs/manual/reference/parameters/#mongodb-parameter-param.minSnapshotHistoryWindowInSeconds)
        /// description in the official documentation.
        /// </summary>
        public readonly int? MinSnapshotHistoryWindowInSeconds;

        [OutputConstructor]
        private MdbMongodbClusterClusterConfigMongodSetParameter(
            bool? auditAuthorizationSuccess,

            bool? enableFlowControl,

            int? minSnapshotHistoryWindowInSeconds)
        {
            AuditAuthorizationSuccess = auditAuthorizationSuccess;
            EnableFlowControl = enableFlowControl;
            MinSnapshotHistoryWindowInSeconds = minSnapshotHistoryWindowInSeconds;
        }
    }
}
