// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class MdbPostgresqlClusterDatabaseExtension
    {
        /// <summary>
        /// Name of the PostgreSQL cluster. Provided by the client when the cluster is created.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Version of the PostgreSQL cluster. (allowed versions are: 10, 10-1c, 11, 11-1c, 12, 12-1c, 13, 13-1c, 14, 14-1c, 15, 15-1c, 16)
        /// </summary>
        public readonly string? Version;

        [OutputConstructor]
        private MdbPostgresqlClusterDatabaseExtension(
            string name,

            string? version)
        {
            Name = name;
            Version = version;
        }
    }
}
