// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class StorageBucketLifecycleRuleFilter
    {
        public readonly Outputs.StorageBucketLifecycleRuleFilterAnd? And;
        public readonly int? ObjectSizeGreaterThan;
        public readonly int? ObjectSizeLessThan;
        /// <summary>
        /// Object key prefix identifying one or more objects to which the rule applies.
        /// </summary>
        public readonly string? Prefix;
        public readonly Outputs.StorageBucketLifecycleRuleFilterTag? Tag;

        [OutputConstructor]
        private StorageBucketLifecycleRuleFilter(
            Outputs.StorageBucketLifecycleRuleFilterAnd? and,

            int? objectSizeGreaterThan,

            int? objectSizeLessThan,

            string? prefix,

            Outputs.StorageBucketLifecycleRuleFilterTag? tag)
        {
            And = and;
            ObjectSizeGreaterThan = objectSizeGreaterThan;
            ObjectSizeLessThan = objectSizeLessThan;
            Prefix = prefix;
            Tag = tag;
        }
    }
}
