// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class SwsSecurityProfileSecurityRuleRuleConditionCondition
    {
        public readonly Outputs.SwsSecurityProfileSecurityRuleRuleConditionConditionAuthority? Authority;
        public readonly ImmutableArray<Outputs.SwsSecurityProfileSecurityRuleRuleConditionConditionHeader> Headers;
        public readonly Outputs.SwsSecurityProfileSecurityRuleRuleConditionConditionHttpMethod? HttpMethod;
        public readonly Outputs.SwsSecurityProfileSecurityRuleRuleConditionConditionRequestUri? RequestUri;
        public readonly Outputs.SwsSecurityProfileSecurityRuleRuleConditionConditionSourceIp? SourceIp;

        [OutputConstructor]
        private SwsSecurityProfileSecurityRuleRuleConditionCondition(
            Outputs.SwsSecurityProfileSecurityRuleRuleConditionConditionAuthority? authority,

            ImmutableArray<Outputs.SwsSecurityProfileSecurityRuleRuleConditionConditionHeader> headers,

            Outputs.SwsSecurityProfileSecurityRuleRuleConditionConditionHttpMethod? httpMethod,

            Outputs.SwsSecurityProfileSecurityRuleRuleConditionConditionRequestUri? requestUri,

            Outputs.SwsSecurityProfileSecurityRuleRuleConditionConditionSourceIp? sourceIp)
        {
            Authority = authority;
            Headers = headers;
            HttpMethod = httpMethod;
            RequestUri = requestUri;
            SourceIp = sourceIp;
        }
    }
}
