// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class SwsSecurityProfileSecurityRule
    {
        public readonly string? Description;
        public readonly bool? DryRun;
        public readonly string? Name;
        public readonly int? Priority;
        public readonly Outputs.SwsSecurityProfileSecurityRuleRuleCondition? RuleCondition;
        public readonly Outputs.SwsSecurityProfileSecurityRuleSmartProtection? SmartProtection;

        [OutputConstructor]
        private SwsSecurityProfileSecurityRule(
            string? description,

            bool? dryRun,

            string? name,

            int? priority,

            Outputs.SwsSecurityProfileSecurityRuleRuleCondition? ruleCondition,

            Outputs.SwsSecurityProfileSecurityRuleSmartProtection? smartProtection)
        {
            Description = description;
            DryRun = dryRun;
            Name = name;
            Priority = priority;
            RuleCondition = ruleCondition;
            SmartProtection = smartProtection;
        }
    }
}
