# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['AuditTrailsTrailArgs', 'AuditTrailsTrail']

@pulumi.input_type
class AuditTrailsTrailArgs:
    def __init__(__self__, *,
                 filter: pulumi.Input['AuditTrailsTrailFilterArgs'],
                 folder_id: pulumi.Input[str],
                 service_account_id: pulumi.Input[str],
                 data_stream_destination: Optional[pulumi.Input['AuditTrailsTrailDataStreamDestinationArgs']] = None,
                 description: Optional[pulumi.Input[str]] = None,
                 labels: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 logging_destination: Optional[pulumi.Input['AuditTrailsTrailLoggingDestinationArgs']] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 storage_destination: Optional[pulumi.Input['AuditTrailsTrailStorageDestinationArgs']] = None):
        """
        The set of arguments for constructing a AuditTrailsTrail resource.
        :param pulumi.Input['AuditTrailsTrailFilterArgs'] filter: Structure describing event filtering process for the trail.
        :param pulumi.Input[str] folder_id: ID of the folder to which the trail belongs.
        :param pulumi.Input[str] service_account_id: ID of the [IAM service account](https://cloud.yandex.ru/en/docs/iam/concepts/users/service-accounts) that is used by the trail.
        :param pulumi.Input['AuditTrailsTrailDataStreamDestinationArgs'] data_stream_destination: Structure describing destination data stream of the trail. Mutually exclusive with `logging_destination` and `storage_destination`.
        :param pulumi.Input[str] description: Description of the trail.
        :param pulumi.Input[Mapping[str, pulumi.Input[str]]] labels: Labels defined by the user.
        :param pulumi.Input['AuditTrailsTrailLoggingDestinationArgs'] logging_destination: Structure describing destination log group of the trail. Mutually exclusive with `storage_destination` and `data_stream_destination`.
        :param pulumi.Input[str] name: Name of the trail.
        :param pulumi.Input['AuditTrailsTrailStorageDestinationArgs'] storage_destination: Structure describing destination bucket of the trail. Mutually exclusive with `logging_destination` and `data_stream_destination`.
        """
        pulumi.set(__self__, "filter", filter)
        pulumi.set(__self__, "folder_id", folder_id)
        pulumi.set(__self__, "service_account_id", service_account_id)
        if data_stream_destination is not None:
            pulumi.set(__self__, "data_stream_destination", data_stream_destination)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if logging_destination is not None:
            pulumi.set(__self__, "logging_destination", logging_destination)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if storage_destination is not None:
            pulumi.set(__self__, "storage_destination", storage_destination)

    @property
    @pulumi.getter
    def filter(self) -> pulumi.Input['AuditTrailsTrailFilterArgs']:
        """
        Structure describing event filtering process for the trail.
        """
        return pulumi.get(self, "filter")

    @filter.setter
    def filter(self, value: pulumi.Input['AuditTrailsTrailFilterArgs']):
        pulumi.set(self, "filter", value)

    @property
    @pulumi.getter(name="folderId")
    def folder_id(self) -> pulumi.Input[str]:
        """
        ID of the folder to which the trail belongs.
        """
        return pulumi.get(self, "folder_id")

    @folder_id.setter
    def folder_id(self, value: pulumi.Input[str]):
        pulumi.set(self, "folder_id", value)

    @property
    @pulumi.getter(name="serviceAccountId")
    def service_account_id(self) -> pulumi.Input[str]:
        """
        ID of the [IAM service account](https://cloud.yandex.ru/en/docs/iam/concepts/users/service-accounts) that is used by the trail.
        """
        return pulumi.get(self, "service_account_id")

    @service_account_id.setter
    def service_account_id(self, value: pulumi.Input[str]):
        pulumi.set(self, "service_account_id", value)

    @property
    @pulumi.getter(name="dataStreamDestination")
    def data_stream_destination(self) -> Optional[pulumi.Input['AuditTrailsTrailDataStreamDestinationArgs']]:
        """
        Structure describing destination data stream of the trail. Mutually exclusive with `logging_destination` and `storage_destination`.
        """
        return pulumi.get(self, "data_stream_destination")

    @data_stream_destination.setter
    def data_stream_destination(self, value: Optional[pulumi.Input['AuditTrailsTrailDataStreamDestinationArgs']]):
        pulumi.set(self, "data_stream_destination", value)

    @property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[str]]:
        """
        Description of the trail.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "description", value)

    @property
    @pulumi.getter
    def labels(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]:
        """
        Labels defined by the user.
        """
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]):
        pulumi.set(self, "labels", value)

    @property
    @pulumi.getter(name="loggingDestination")
    def logging_destination(self) -> Optional[pulumi.Input['AuditTrailsTrailLoggingDestinationArgs']]:
        """
        Structure describing destination log group of the trail. Mutually exclusive with `storage_destination` and `data_stream_destination`.
        """
        return pulumi.get(self, "logging_destination")

    @logging_destination.setter
    def logging_destination(self, value: Optional[pulumi.Input['AuditTrailsTrailLoggingDestinationArgs']]):
        pulumi.set(self, "logging_destination", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        Name of the trail.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="storageDestination")
    def storage_destination(self) -> Optional[pulumi.Input['AuditTrailsTrailStorageDestinationArgs']]:
        """
        Structure describing destination bucket of the trail. Mutually exclusive with `logging_destination` and `data_stream_destination`.
        """
        return pulumi.get(self, "storage_destination")

    @storage_destination.setter
    def storage_destination(self, value: Optional[pulumi.Input['AuditTrailsTrailStorageDestinationArgs']]):
        pulumi.set(self, "storage_destination", value)


@pulumi.input_type
class _AuditTrailsTrailState:
    def __init__(__self__, *,
                 data_stream_destination: Optional[pulumi.Input['AuditTrailsTrailDataStreamDestinationArgs']] = None,
                 description: Optional[pulumi.Input[str]] = None,
                 filter: Optional[pulumi.Input['AuditTrailsTrailFilterArgs']] = None,
                 folder_id: Optional[pulumi.Input[str]] = None,
                 labels: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 logging_destination: Optional[pulumi.Input['AuditTrailsTrailLoggingDestinationArgs']] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 service_account_id: Optional[pulumi.Input[str]] = None,
                 status: Optional[pulumi.Input[str]] = None,
                 storage_destination: Optional[pulumi.Input['AuditTrailsTrailStorageDestinationArgs']] = None,
                 trail_id: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering AuditTrailsTrail resources.
        :param pulumi.Input['AuditTrailsTrailDataStreamDestinationArgs'] data_stream_destination: Structure describing destination data stream of the trail. Mutually exclusive with `logging_destination` and `storage_destination`.
        :param pulumi.Input[str] description: Description of the trail.
        :param pulumi.Input['AuditTrailsTrailFilterArgs'] filter: Structure describing event filtering process for the trail.
        :param pulumi.Input[str] folder_id: ID of the folder to which the trail belongs.
        :param pulumi.Input[Mapping[str, pulumi.Input[str]]] labels: Labels defined by the user.
        :param pulumi.Input['AuditTrailsTrailLoggingDestinationArgs'] logging_destination: Structure describing destination log group of the trail. Mutually exclusive with `storage_destination` and `data_stream_destination`.
        :param pulumi.Input[str] name: Name of the trail.
        :param pulumi.Input[str] service_account_id: ID of the [IAM service account](https://cloud.yandex.ru/en/docs/iam/concepts/users/service-accounts) that is used by the trail.
        :param pulumi.Input[str] status: Status of this trail.
        :param pulumi.Input['AuditTrailsTrailStorageDestinationArgs'] storage_destination: Structure describing destination bucket of the trail. Mutually exclusive with `logging_destination` and `data_stream_destination`.
        :param pulumi.Input[str] trail_id: ID of the trail resource.
        """
        if data_stream_destination is not None:
            pulumi.set(__self__, "data_stream_destination", data_stream_destination)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if filter is not None:
            pulumi.set(__self__, "filter", filter)
        if folder_id is not None:
            pulumi.set(__self__, "folder_id", folder_id)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if logging_destination is not None:
            pulumi.set(__self__, "logging_destination", logging_destination)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if service_account_id is not None:
            pulumi.set(__self__, "service_account_id", service_account_id)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if storage_destination is not None:
            pulumi.set(__self__, "storage_destination", storage_destination)
        if trail_id is not None:
            pulumi.set(__self__, "trail_id", trail_id)

    @property
    @pulumi.getter(name="dataStreamDestination")
    def data_stream_destination(self) -> Optional[pulumi.Input['AuditTrailsTrailDataStreamDestinationArgs']]:
        """
        Structure describing destination data stream of the trail. Mutually exclusive with `logging_destination` and `storage_destination`.
        """
        return pulumi.get(self, "data_stream_destination")

    @data_stream_destination.setter
    def data_stream_destination(self, value: Optional[pulumi.Input['AuditTrailsTrailDataStreamDestinationArgs']]):
        pulumi.set(self, "data_stream_destination", value)

    @property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[str]]:
        """
        Description of the trail.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "description", value)

    @property
    @pulumi.getter
    def filter(self) -> Optional[pulumi.Input['AuditTrailsTrailFilterArgs']]:
        """
        Structure describing event filtering process for the trail.
        """
        return pulumi.get(self, "filter")

    @filter.setter
    def filter(self, value: Optional[pulumi.Input['AuditTrailsTrailFilterArgs']]):
        pulumi.set(self, "filter", value)

    @property
    @pulumi.getter(name="folderId")
    def folder_id(self) -> Optional[pulumi.Input[str]]:
        """
        ID of the folder to which the trail belongs.
        """
        return pulumi.get(self, "folder_id")

    @folder_id.setter
    def folder_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "folder_id", value)

    @property
    @pulumi.getter
    def labels(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]:
        """
        Labels defined by the user.
        """
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]):
        pulumi.set(self, "labels", value)

    @property
    @pulumi.getter(name="loggingDestination")
    def logging_destination(self) -> Optional[pulumi.Input['AuditTrailsTrailLoggingDestinationArgs']]:
        """
        Structure describing destination log group of the trail. Mutually exclusive with `storage_destination` and `data_stream_destination`.
        """
        return pulumi.get(self, "logging_destination")

    @logging_destination.setter
    def logging_destination(self, value: Optional[pulumi.Input['AuditTrailsTrailLoggingDestinationArgs']]):
        pulumi.set(self, "logging_destination", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        Name of the trail.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="serviceAccountId")
    def service_account_id(self) -> Optional[pulumi.Input[str]]:
        """
        ID of the [IAM service account](https://cloud.yandex.ru/en/docs/iam/concepts/users/service-accounts) that is used by the trail.
        """
        return pulumi.get(self, "service_account_id")

    @service_account_id.setter
    def service_account_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "service_account_id", value)

    @property
    @pulumi.getter
    def status(self) -> Optional[pulumi.Input[str]]:
        """
        Status of this trail.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "status", value)

    @property
    @pulumi.getter(name="storageDestination")
    def storage_destination(self) -> Optional[pulumi.Input['AuditTrailsTrailStorageDestinationArgs']]:
        """
        Structure describing destination bucket of the trail. Mutually exclusive with `logging_destination` and `data_stream_destination`.
        """
        return pulumi.get(self, "storage_destination")

    @storage_destination.setter
    def storage_destination(self, value: Optional[pulumi.Input['AuditTrailsTrailStorageDestinationArgs']]):
        pulumi.set(self, "storage_destination", value)

    @property
    @pulumi.getter(name="trailId")
    def trail_id(self) -> Optional[pulumi.Input[str]]:
        """
        ID of the trail resource.
        """
        return pulumi.get(self, "trail_id")

    @trail_id.setter
    def trail_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "trail_id", value)


class AuditTrailsTrail(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 data_stream_destination: Optional[pulumi.Input[pulumi.InputType['AuditTrailsTrailDataStreamDestinationArgs']]] = None,
                 description: Optional[pulumi.Input[str]] = None,
                 filter: Optional[pulumi.Input[pulumi.InputType['AuditTrailsTrailFilterArgs']]] = None,
                 folder_id: Optional[pulumi.Input[str]] = None,
                 labels: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 logging_destination: Optional[pulumi.Input[pulumi.InputType['AuditTrailsTrailLoggingDestinationArgs']]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 service_account_id: Optional[pulumi.Input[str]] = None,
                 storage_destination: Optional[pulumi.Input[pulumi.InputType['AuditTrailsTrailStorageDestinationArgs']]] = None,
                 __props__=None):
        """
        Allows management of [trail](https://cloud.yandex.ru/en/docs/audit-trails/concepts/trail)

        ## Example Usage

        Trail delivering logs to Cloud Logging and gathering such logs:

        * Control plane logs from the 'home-folder' folder
        * Object Storage data plane logs from the 'home-folder' folder
        * DNS data plane logs from networks in the 'home-folder' folder
        <!--Start PulumiCodeChooser -->
        ```python
        import pulumi
        import pulumi_yandex as yandex

        basic_trail = yandex.AuditTrailsTrail("basicTrail",
            description="Some trail description",
            filter=yandex.AuditTrailsTrailFilterArgs(
                event_filters=[
                    yandex.AuditTrailsTrailFilterEventFilterArgs(
                        categories=[yandex.AuditTrailsTrailFilterEventFilterCategoryArgs(
                            plane="DATA_PLANE",
                            type="WRITE",
                        )],
                        path_filter=yandex.AuditTrailsTrailFilterEventFilterPathFilterArgs(
                            any_filter=yandex.AuditTrailsTrailFilterEventFilterPathFilterAnyFilterArgs(
                                resource_id="home-folder",
                                resource_type="resource-manager.folder",
                            ),
                        ),
                        service="storage",
                    ),
                    yandex.AuditTrailsTrailFilterEventFilterArgs(
                        categories=[yandex.AuditTrailsTrailFilterEventFilterCategoryArgs(
                            plane="DATA_PLANE",
                            type="READ",
                        )],
                        path_filter=yandex.AuditTrailsTrailFilterEventFilterPathFilterArgs(
                            some_filter=yandex.AuditTrailsTrailFilterEventFilterPathFilterSomeFilterArgs(
                                any_filters=[
                                    yandex.AuditTrailsTrailFilterEventFilterPathFilterSomeFilterAnyFilterArgs(
                                        resource_id="vpc-net-id-1",
                                        resource_type="vpc.network",
                                    ),
                                    yandex.AuditTrailsTrailFilterEventFilterPathFilterSomeFilterAnyFilterArgs(
                                        resource_id="vpc-net-id-2",
                                        resource_type="vpc.network",
                                    ),
                                ],
                                resource_id="home-folder",
                                resource_type="resource-manager.folder",
                            ),
                        ),
                        service="dns",
                    ),
                ],
                path_filter=yandex.AuditTrailsTrailFilterPathFilterArgs(
                    any_filter=yandex.AuditTrailsTrailFilterPathFilterAnyFilterArgs(
                        resource_id="home-folder",
                        resource_type="resource-manager.folder",
                    ),
                ),
            ),
            folder_id="home-folder",
            labels={
                "key": "value",
            },
            logging_destination=yandex.AuditTrailsTrailLoggingDestinationArgs(
                log_group_id="some-log-group",
            ),
            service_account_id="trail-service-account")
        ```
        <!--End PulumiCodeChooser -->

        Trail delivering logs to YDS and gathering such logs:

        * Control plane logs from the 'some-organization' organization
        * DNS data plane logs from the 'some-organization' organization
        * Object Storage data plane logs from the 'some-organization' organization
        <!--Start PulumiCodeChooser -->
        ```python
        import pulumi
        import pulumi_yandex as yandex

        basic_trail = yandex.AuditTrailsTrail("basicTrail",
            data_stream_destination=yandex.AuditTrailsTrailDataStreamDestinationArgs(
                database_id="some-database",
                stream_name="some-stream",
            ),
            description="Some trail description",
            filter=yandex.AuditTrailsTrailFilterArgs(
                event_filters=[
                    yandex.AuditTrailsTrailFilterEventFilterArgs(
                        categories=[yandex.AuditTrailsTrailFilterEventFilterCategoryArgs(
                            plane="DATA_PLANE",
                            type="WRITE",
                        )],
                        path_filter=yandex.AuditTrailsTrailFilterEventFilterPathFilterArgs(
                            any_filter=yandex.AuditTrailsTrailFilterEventFilterPathFilterAnyFilterArgs(
                                resource_id="some-organization",
                                resource_type="organization-manager.organization",
                            ),
                        ),
                        service="storage",
                    ),
                    yandex.AuditTrailsTrailFilterEventFilterArgs(
                        categories=[yandex.AuditTrailsTrailFilterEventFilterCategoryArgs(
                            plane="DATA_PLANE",
                            type="READ",
                        )],
                        path_filter=yandex.AuditTrailsTrailFilterEventFilterPathFilterArgs(
                            any_filter=yandex.AuditTrailsTrailFilterEventFilterPathFilterAnyFilterArgs(
                                resource_id="some-organization",
                                resource_type="organization-manager.organization",
                            ),
                        ),
                        service="dns",
                    ),
                ],
                path_filter=yandex.AuditTrailsTrailFilterPathFilterArgs(
                    any_filter=yandex.AuditTrailsTrailFilterPathFilterAnyFilterArgs(
                        resource_id="some-organization",
                        resource_type="organization-manager.organization",
                    ),
                ),
            ),
            folder_id="home-folder",
            labels={
                "key": "value",
            },
            service_account_id="trail-service-account")
        ```
        <!--End PulumiCodeChooser -->

        Trail delivering logs to Object Storage and gathering such logs:

        * Control plane logs from the 'home-folder' folder
        * Managed PostgreSQL data plane logs from the 'home-folder' folder
        <!--Start PulumiCodeChooser -->
        ```python
        import pulumi
        import pulumi_yandex as yandex

        basic_trail = yandex.AuditTrailsTrail("basicTrail",
            description="Some trail description",
            filter=yandex.AuditTrailsTrailFilterArgs(
                event_filters=[yandex.AuditTrailsTrailFilterEventFilterArgs(
                    categories=[yandex.AuditTrailsTrailFilterEventFilterCategoryArgs(
                        plane="DATA_PLANE",
                        type="WRITE",
                    )],
                    path_filter=yandex.AuditTrailsTrailFilterEventFilterPathFilterArgs(
                        any_filter=yandex.AuditTrailsTrailFilterEventFilterPathFilterAnyFilterArgs(
                            resource_id="home-folder",
                            resource_type="resource-manager.folder",
                        ),
                    ),
                    service="mdb.postgresql",
                )],
                path_filter=yandex.AuditTrailsTrailFilterPathFilterArgs(
                    any_filter=yandex.AuditTrailsTrailFilterPathFilterAnyFilterArgs(
                        resource_id="home-folder",
                        resource_type="resource-manager.folder",
                    ),
                ),
            ),
            folder_id="home-folder",
            labels={
                "key": "value",
            },
            service_account_id="trail-service-account",
            storage_destination=yandex.AuditTrailsTrailStorageDestinationArgs(
                bucket_name="some-bucket",
                object_prefix="some-prefix",
            ))
        ```
        <!--End PulumiCodeChooser -->

        ## Import

        A trail can be imported using the `id` of the resource, e.g.

        bash

        ```sh
        $ pulumi import yandex:index/auditTrailsTrail:AuditTrailsTrail infosec-trail trail_id
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[pulumi.InputType['AuditTrailsTrailDataStreamDestinationArgs']] data_stream_destination: Structure describing destination data stream of the trail. Mutually exclusive with `logging_destination` and `storage_destination`.
        :param pulumi.Input[str] description: Description of the trail.
        :param pulumi.Input[pulumi.InputType['AuditTrailsTrailFilterArgs']] filter: Structure describing event filtering process for the trail.
        :param pulumi.Input[str] folder_id: ID of the folder to which the trail belongs.
        :param pulumi.Input[Mapping[str, pulumi.Input[str]]] labels: Labels defined by the user.
        :param pulumi.Input[pulumi.InputType['AuditTrailsTrailLoggingDestinationArgs']] logging_destination: Structure describing destination log group of the trail. Mutually exclusive with `storage_destination` and `data_stream_destination`.
        :param pulumi.Input[str] name: Name of the trail.
        :param pulumi.Input[str] service_account_id: ID of the [IAM service account](https://cloud.yandex.ru/en/docs/iam/concepts/users/service-accounts) that is used by the trail.
        :param pulumi.Input[pulumi.InputType['AuditTrailsTrailStorageDestinationArgs']] storage_destination: Structure describing destination bucket of the trail. Mutually exclusive with `logging_destination` and `data_stream_destination`.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: AuditTrailsTrailArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Allows management of [trail](https://cloud.yandex.ru/en/docs/audit-trails/concepts/trail)

        ## Example Usage

        Trail delivering logs to Cloud Logging and gathering such logs:

        * Control plane logs from the 'home-folder' folder
        * Object Storage data plane logs from the 'home-folder' folder
        * DNS data plane logs from networks in the 'home-folder' folder
        <!--Start PulumiCodeChooser -->
        ```python
        import pulumi
        import pulumi_yandex as yandex

        basic_trail = yandex.AuditTrailsTrail("basicTrail",
            description="Some trail description",
            filter=yandex.AuditTrailsTrailFilterArgs(
                event_filters=[
                    yandex.AuditTrailsTrailFilterEventFilterArgs(
                        categories=[yandex.AuditTrailsTrailFilterEventFilterCategoryArgs(
                            plane="DATA_PLANE",
                            type="WRITE",
                        )],
                        path_filter=yandex.AuditTrailsTrailFilterEventFilterPathFilterArgs(
                            any_filter=yandex.AuditTrailsTrailFilterEventFilterPathFilterAnyFilterArgs(
                                resource_id="home-folder",
                                resource_type="resource-manager.folder",
                            ),
                        ),
                        service="storage",
                    ),
                    yandex.AuditTrailsTrailFilterEventFilterArgs(
                        categories=[yandex.AuditTrailsTrailFilterEventFilterCategoryArgs(
                            plane="DATA_PLANE",
                            type="READ",
                        )],
                        path_filter=yandex.AuditTrailsTrailFilterEventFilterPathFilterArgs(
                            some_filter=yandex.AuditTrailsTrailFilterEventFilterPathFilterSomeFilterArgs(
                                any_filters=[
                                    yandex.AuditTrailsTrailFilterEventFilterPathFilterSomeFilterAnyFilterArgs(
                                        resource_id="vpc-net-id-1",
                                        resource_type="vpc.network",
                                    ),
                                    yandex.AuditTrailsTrailFilterEventFilterPathFilterSomeFilterAnyFilterArgs(
                                        resource_id="vpc-net-id-2",
                                        resource_type="vpc.network",
                                    ),
                                ],
                                resource_id="home-folder",
                                resource_type="resource-manager.folder",
                            ),
                        ),
                        service="dns",
                    ),
                ],
                path_filter=yandex.AuditTrailsTrailFilterPathFilterArgs(
                    any_filter=yandex.AuditTrailsTrailFilterPathFilterAnyFilterArgs(
                        resource_id="home-folder",
                        resource_type="resource-manager.folder",
                    ),
                ),
            ),
            folder_id="home-folder",
            labels={
                "key": "value",
            },
            logging_destination=yandex.AuditTrailsTrailLoggingDestinationArgs(
                log_group_id="some-log-group",
            ),
            service_account_id="trail-service-account")
        ```
        <!--End PulumiCodeChooser -->

        Trail delivering logs to YDS and gathering such logs:

        * Control plane logs from the 'some-organization' organization
        * DNS data plane logs from the 'some-organization' organization
        * Object Storage data plane logs from the 'some-organization' organization
        <!--Start PulumiCodeChooser -->
        ```python
        import pulumi
        import pulumi_yandex as yandex

        basic_trail = yandex.AuditTrailsTrail("basicTrail",
            data_stream_destination=yandex.AuditTrailsTrailDataStreamDestinationArgs(
                database_id="some-database",
                stream_name="some-stream",
            ),
            description="Some trail description",
            filter=yandex.AuditTrailsTrailFilterArgs(
                event_filters=[
                    yandex.AuditTrailsTrailFilterEventFilterArgs(
                        categories=[yandex.AuditTrailsTrailFilterEventFilterCategoryArgs(
                            plane="DATA_PLANE",
                            type="WRITE",
                        )],
                        path_filter=yandex.AuditTrailsTrailFilterEventFilterPathFilterArgs(
                            any_filter=yandex.AuditTrailsTrailFilterEventFilterPathFilterAnyFilterArgs(
                                resource_id="some-organization",
                                resource_type="organization-manager.organization",
                            ),
                        ),
                        service="storage",
                    ),
                    yandex.AuditTrailsTrailFilterEventFilterArgs(
                        categories=[yandex.AuditTrailsTrailFilterEventFilterCategoryArgs(
                            plane="DATA_PLANE",
                            type="READ",
                        )],
                        path_filter=yandex.AuditTrailsTrailFilterEventFilterPathFilterArgs(
                            any_filter=yandex.AuditTrailsTrailFilterEventFilterPathFilterAnyFilterArgs(
                                resource_id="some-organization",
                                resource_type="organization-manager.organization",
                            ),
                        ),
                        service="dns",
                    ),
                ],
                path_filter=yandex.AuditTrailsTrailFilterPathFilterArgs(
                    any_filter=yandex.AuditTrailsTrailFilterPathFilterAnyFilterArgs(
                        resource_id="some-organization",
                        resource_type="organization-manager.organization",
                    ),
                ),
            ),
            folder_id="home-folder",
            labels={
                "key": "value",
            },
            service_account_id="trail-service-account")
        ```
        <!--End PulumiCodeChooser -->

        Trail delivering logs to Object Storage and gathering such logs:

        * Control plane logs from the 'home-folder' folder
        * Managed PostgreSQL data plane logs from the 'home-folder' folder
        <!--Start PulumiCodeChooser -->
        ```python
        import pulumi
        import pulumi_yandex as yandex

        basic_trail = yandex.AuditTrailsTrail("basicTrail",
            description="Some trail description",
            filter=yandex.AuditTrailsTrailFilterArgs(
                event_filters=[yandex.AuditTrailsTrailFilterEventFilterArgs(
                    categories=[yandex.AuditTrailsTrailFilterEventFilterCategoryArgs(
                        plane="DATA_PLANE",
                        type="WRITE",
                    )],
                    path_filter=yandex.AuditTrailsTrailFilterEventFilterPathFilterArgs(
                        any_filter=yandex.AuditTrailsTrailFilterEventFilterPathFilterAnyFilterArgs(
                            resource_id="home-folder",
                            resource_type="resource-manager.folder",
                        ),
                    ),
                    service="mdb.postgresql",
                )],
                path_filter=yandex.AuditTrailsTrailFilterPathFilterArgs(
                    any_filter=yandex.AuditTrailsTrailFilterPathFilterAnyFilterArgs(
                        resource_id="home-folder",
                        resource_type="resource-manager.folder",
                    ),
                ),
            ),
            folder_id="home-folder",
            labels={
                "key": "value",
            },
            service_account_id="trail-service-account",
            storage_destination=yandex.AuditTrailsTrailStorageDestinationArgs(
                bucket_name="some-bucket",
                object_prefix="some-prefix",
            ))
        ```
        <!--End PulumiCodeChooser -->

        ## Import

        A trail can be imported using the `id` of the resource, e.g.

        bash

        ```sh
        $ pulumi import yandex:index/auditTrailsTrail:AuditTrailsTrail infosec-trail trail_id
        ```

        :param str resource_name: The name of the resource.
        :param AuditTrailsTrailArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(AuditTrailsTrailArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 data_stream_destination: Optional[pulumi.Input[pulumi.InputType['AuditTrailsTrailDataStreamDestinationArgs']]] = None,
                 description: Optional[pulumi.Input[str]] = None,
                 filter: Optional[pulumi.Input[pulumi.InputType['AuditTrailsTrailFilterArgs']]] = None,
                 folder_id: Optional[pulumi.Input[str]] = None,
                 labels: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 logging_destination: Optional[pulumi.Input[pulumi.InputType['AuditTrailsTrailLoggingDestinationArgs']]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 service_account_id: Optional[pulumi.Input[str]] = None,
                 storage_destination: Optional[pulumi.Input[pulumi.InputType['AuditTrailsTrailStorageDestinationArgs']]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = AuditTrailsTrailArgs.__new__(AuditTrailsTrailArgs)

            __props__.__dict__["data_stream_destination"] = data_stream_destination
            __props__.__dict__["description"] = description
            if filter is None and not opts.urn:
                raise TypeError("Missing required property 'filter'")
            __props__.__dict__["filter"] = filter
            if folder_id is None and not opts.urn:
                raise TypeError("Missing required property 'folder_id'")
            __props__.__dict__["folder_id"] = folder_id
            __props__.__dict__["labels"] = labels
            __props__.__dict__["logging_destination"] = logging_destination
            __props__.__dict__["name"] = name
            if service_account_id is None and not opts.urn:
                raise TypeError("Missing required property 'service_account_id'")
            __props__.__dict__["service_account_id"] = service_account_id
            __props__.__dict__["storage_destination"] = storage_destination
            __props__.__dict__["status"] = None
            __props__.__dict__["trail_id"] = None
        super(AuditTrailsTrail, __self__).__init__(
            'yandex:index/auditTrailsTrail:AuditTrailsTrail',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            data_stream_destination: Optional[pulumi.Input[pulumi.InputType['AuditTrailsTrailDataStreamDestinationArgs']]] = None,
            description: Optional[pulumi.Input[str]] = None,
            filter: Optional[pulumi.Input[pulumi.InputType['AuditTrailsTrailFilterArgs']]] = None,
            folder_id: Optional[pulumi.Input[str]] = None,
            labels: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
            logging_destination: Optional[pulumi.Input[pulumi.InputType['AuditTrailsTrailLoggingDestinationArgs']]] = None,
            name: Optional[pulumi.Input[str]] = None,
            service_account_id: Optional[pulumi.Input[str]] = None,
            status: Optional[pulumi.Input[str]] = None,
            storage_destination: Optional[pulumi.Input[pulumi.InputType['AuditTrailsTrailStorageDestinationArgs']]] = None,
            trail_id: Optional[pulumi.Input[str]] = None) -> 'AuditTrailsTrail':
        """
        Get an existing AuditTrailsTrail resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[pulumi.InputType['AuditTrailsTrailDataStreamDestinationArgs']] data_stream_destination: Structure describing destination data stream of the trail. Mutually exclusive with `logging_destination` and `storage_destination`.
        :param pulumi.Input[str] description: Description of the trail.
        :param pulumi.Input[pulumi.InputType['AuditTrailsTrailFilterArgs']] filter: Structure describing event filtering process for the trail.
        :param pulumi.Input[str] folder_id: ID of the folder to which the trail belongs.
        :param pulumi.Input[Mapping[str, pulumi.Input[str]]] labels: Labels defined by the user.
        :param pulumi.Input[pulumi.InputType['AuditTrailsTrailLoggingDestinationArgs']] logging_destination: Structure describing destination log group of the trail. Mutually exclusive with `storage_destination` and `data_stream_destination`.
        :param pulumi.Input[str] name: Name of the trail.
        :param pulumi.Input[str] service_account_id: ID of the [IAM service account](https://cloud.yandex.ru/en/docs/iam/concepts/users/service-accounts) that is used by the trail.
        :param pulumi.Input[str] status: Status of this trail.
        :param pulumi.Input[pulumi.InputType['AuditTrailsTrailStorageDestinationArgs']] storage_destination: Structure describing destination bucket of the trail. Mutually exclusive with `logging_destination` and `data_stream_destination`.
        :param pulumi.Input[str] trail_id: ID of the trail resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _AuditTrailsTrailState.__new__(_AuditTrailsTrailState)

        __props__.__dict__["data_stream_destination"] = data_stream_destination
        __props__.__dict__["description"] = description
        __props__.__dict__["filter"] = filter
        __props__.__dict__["folder_id"] = folder_id
        __props__.__dict__["labels"] = labels
        __props__.__dict__["logging_destination"] = logging_destination
        __props__.__dict__["name"] = name
        __props__.__dict__["service_account_id"] = service_account_id
        __props__.__dict__["status"] = status
        __props__.__dict__["storage_destination"] = storage_destination
        __props__.__dict__["trail_id"] = trail_id
        return AuditTrailsTrail(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="dataStreamDestination")
    def data_stream_destination(self) -> pulumi.Output[Optional['outputs.AuditTrailsTrailDataStreamDestination']]:
        """
        Structure describing destination data stream of the trail. Mutually exclusive with `logging_destination` and `storage_destination`.
        """
        return pulumi.get(self, "data_stream_destination")

    @property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[str]]:
        """
        Description of the trail.
        """
        return pulumi.get(self, "description")

    @property
    @pulumi.getter
    def filter(self) -> pulumi.Output['outputs.AuditTrailsTrailFilter']:
        """
        Structure describing event filtering process for the trail.
        """
        return pulumi.get(self, "filter")

    @property
    @pulumi.getter(name="folderId")
    def folder_id(self) -> pulumi.Output[str]:
        """
        ID of the folder to which the trail belongs.
        """
        return pulumi.get(self, "folder_id")

    @property
    @pulumi.getter
    def labels(self) -> pulumi.Output[Optional[Mapping[str, str]]]:
        """
        Labels defined by the user.
        """
        return pulumi.get(self, "labels")

    @property
    @pulumi.getter(name="loggingDestination")
    def logging_destination(self) -> pulumi.Output[Optional['outputs.AuditTrailsTrailLoggingDestination']]:
        """
        Structure describing destination log group of the trail. Mutually exclusive with `storage_destination` and `data_stream_destination`.
        """
        return pulumi.get(self, "logging_destination")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[str]:
        """
        Name of the trail.
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter(name="serviceAccountId")
    def service_account_id(self) -> pulumi.Output[str]:
        """
        ID of the [IAM service account](https://cloud.yandex.ru/en/docs/iam/concepts/users/service-accounts) that is used by the trail.
        """
        return pulumi.get(self, "service_account_id")

    @property
    @pulumi.getter
    def status(self) -> pulumi.Output[str]:
        """
        Status of this trail.
        """
        return pulumi.get(self, "status")

    @property
    @pulumi.getter(name="storageDestination")
    def storage_destination(self) -> pulumi.Output[Optional['outputs.AuditTrailsTrailStorageDestination']]:
        """
        Structure describing destination bucket of the trail. Mutually exclusive with `logging_destination` and `data_stream_destination`.
        """
        return pulumi.get(self, "storage_destination")

    @property
    @pulumi.getter(name="trailId")
    def trail_id(self) -> pulumi.Output[str]:
        """
        ID of the trail resource.
        """
        return pulumi.get(self, "trail_id")

