// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class AuditTrailsTrailFilterPathFilterSomeFilterArgs : global::Pulumi.ResourceArgs
    {
        [Input("anyFilters", required: true)]
        private InputList<Inputs.AuditTrailsTrailFilterPathFilterSomeFilterAnyFilterArgs>? _anyFilters;

        /// <summary>
        /// List of child resources from which events will be gathered
        /// </summary>
        public InputList<Inputs.AuditTrailsTrailFilterPathFilterSomeFilterAnyFilterArgs> AnyFilters
        {
            get => _anyFilters ?? (_anyFilters = new InputList<Inputs.AuditTrailsTrailFilterPathFilterSomeFilterAnyFilterArgs>());
            set => _anyFilters = value;
        }

        /// <summary>
        /// ID of the child resource.
        /// </summary>
        [Input("resourceId", required: true)]
        public Input<string> ResourceId { get; set; } = null!;

        /// <summary>
        /// Resource type of the child resource.
        /// </summary>
        [Input("resourceType", required: true)]
        public Input<string> ResourceType { get; set; } = null!;

        public AuditTrailsTrailFilterPathFilterSomeFilterArgs()
        {
        }
        public static new AuditTrailsTrailFilterPathFilterSomeFilterArgs Empty => new AuditTrailsTrailFilterPathFilterSomeFilterArgs();
    }
}
