// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class DatatransferTransferTransformationTransformerConvertToStringColumnsArgs : global::Pulumi.ResourceArgs
    {
        [Input("excludeColumns")]
        private InputList<string>? _excludeColumns;

        /// <summary>
        /// List of columns that will be excluded to transfer.
        /// </summary>
        public InputList<string> ExcludeColumns
        {
            get => _excludeColumns ?? (_excludeColumns = new InputList<string>());
            set => _excludeColumns = value;
        }

        [Input("includeColumns")]
        private InputList<string>? _includeColumns;

        /// <summary>
        /// List of columns that will be included to transfer.
        /// </summary>
        public InputList<string> IncludeColumns
        {
            get => _includeColumns ?? (_includeColumns = new InputList<string>());
            set => _includeColumns = value;
        }

        public DatatransferTransferTransformationTransformerConvertToStringColumnsArgs()
        {
        }
        public static new DatatransferTransferTransformationTransformerConvertToStringColumnsArgs Empty => new DatatransferTransferTransformationTransformerConvertToStringColumnsArgs();
    }
}
