// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class DatatransferEndpointSettingsYdsSourceParserAuditTrailsV1ParserGetArgs : global::Pulumi.ResourceArgs
    {
        public DatatransferEndpointSettingsYdsSourceParserAuditTrailsV1ParserGetArgs()
        {
        }
        public static new DatatransferEndpointSettingsYdsSourceParserAuditTrailsV1ParserGetArgs Empty => new DatatransferEndpointSettingsYdsSourceParserAuditTrailsV1ParserGetArgs();
    }
}
