// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class DatatransferTransferTransformationTransformerRenameTablesRenameTableOriginalNameGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the transfer.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("nameSpace")]
        public Input<string>? NameSpace { get; set; }

        public DatatransferTransferTransformationTransformerRenameTablesRenameTableOriginalNameGetArgs()
        {
        }
        public static new DatatransferTransferTransformationTransformerRenameTablesRenameTableOriginalNameGetArgs Empty => new DatatransferTransferTransformationTransformerRenameTablesRenameTableOriginalNameGetArgs();
    }
}
