// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class FunctionStorageMountArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// (Required) Name of the mounting bucket.
        /// </summary>
        [Input("bucket", required: true)]
        public Input<string> Bucket { get; set; } = null!;

        /// <summary>
        /// (Required) Name of the mount point. The directory where the bucket is mounted will be accessible at the `/function/storage/&lt;mount_point&gt;` path.
        /// </summary>
        [Input("mountPointName", required: true)]
        public Input<string> MountPointName { get; set; } = null!;

        /// <summary>
        /// Prefix within the bucket. If you leave this field empty, the entire bucket will be mounted.
        /// </summary>
        [Input("prefix")]
        public Input<string>? Prefix { get; set; }

        /// <summary>
        /// Mount the bucket in read-only mode.
        /// </summary>
        [Input("readOnly")]
        public Input<bool>? ReadOnly { get; set; }

        public FunctionStorageMountArgs()
        {
        }
        public static new FunctionStorageMountArgs Empty => new FunctionStorageMountArgs();
    }
}
