// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class GetAlbBackendGroupSessionAffinityCookieArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Name of the HTTP cookie
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        /// <summary>
        /// TTL for the cookie (if not set, session cookie will be used)
        /// </summary>
        [Input("ttl", required: true)]
        public string Ttl { get; set; } = null!;

        public GetAlbBackendGroupSessionAffinityCookieArgs()
        {
        }
        public static new GetAlbBackendGroupSessionAffinityCookieArgs Empty => new GetAlbBackendGroupSessionAffinityCookieArgs();
    }
}
