// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class GetFunctionStorageMountArgs : global::Pulumi.InvokeArgs
    {
        [Input("bucket", required: true)]
        public string Bucket { get; set; } = null!;

        [Input("mountPointName", required: true)]
        public string MountPointName { get; set; } = null!;

        [Input("prefix")]
        public string? Prefix { get; set; }

        [Input("readOnly")]
        public bool? ReadOnly { get; set; }

        public GetFunctionStorageMountArgs()
        {
        }
        public static new GetFunctionStorageMountArgs Empty => new GetFunctionStorageMountArgs();
    }
}
