// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class GetMdbClickhouseClusterUserQuotaArgs : global::Pulumi.InvokeArgs
    {
        [Input("errors", required: true)]
        public int Errors { get; set; }

        [Input("executionTime", required: true)]
        public int ExecutionTime { get; set; }

        [Input("intervalDuration")]
        public int? IntervalDuration { get; set; }

        [Input("queries", required: true)]
        public int Queries { get; set; }

        [Input("readRows", required: true)]
        public int ReadRows { get; set; }

        [Input("resultRows", required: true)]
        public int ResultRows { get; set; }

        public GetMdbClickhouseClusterUserQuotaArgs()
        {
        }
        public static new GetMdbClickhouseClusterUserQuotaArgs Empty => new GetMdbClickhouseClusterUserQuotaArgs();
    }
}
