// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class GetMdbClickhouseClusterShardInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("resources", required: true)]
        public Input<Inputs.GetMdbClickhouseClusterShardResourcesInputArgs> Resources { get; set; } = null!;

        [Input("weight", required: true)]
        public Input<int> Weight { get; set; } = null!;

        public GetMdbClickhouseClusterShardInputArgs()
        {
        }
        public static new GetMdbClickhouseClusterShardInputArgs Empty => new GetMdbClickhouseClusterShardInputArgs();
    }
}
