// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class GetMdbClickhouseClusterHostArgs : global::Pulumi.InvokeArgs
    {
        [Input("assignPublicIp")]
        public bool? AssignPublicIp { get; set; }

        [Input("fqdn", required: true)]
        public string Fqdn { get; set; } = null!;

        [Input("shardName", required: true)]
        public string ShardName { get; set; } = null!;

        [Input("subnetId", required: true)]
        public string SubnetId { get; set; } = null!;

        [Input("type")]
        public string? Type { get; set; }

        [Input("zone")]
        public string? Zone { get; set; }

        public GetMdbClickhouseClusterHostArgs()
        {
        }
        public static new GetMdbClickhouseClusterHostArgs Empty => new GetMdbClickhouseClusterHostArgs();
    }
}
