// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class GetMdbClickhouseClusterMlModelArgs : global::Pulumi.InvokeArgs
    {
        [Input("name")]
        public string? Name { get; set; }

        [Input("type")]
        public string? Type { get; set; }

        [Input("uri")]
        public string? Uri { get; set; }

        public GetMdbClickhouseClusterMlModelArgs()
        {
        }
        public static new GetMdbClickhouseClusterMlModelArgs Empty => new GetMdbClickhouseClusterMlModelArgs();
    }
}
