// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class GetMdbClickhouseClusterShardGroupArgs : global::Pulumi.InvokeArgs
    {
        [Input("description")]
        public string? Description { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        [Input("shardNames")]
        private List<string>? _shardNames;
        public List<string> ShardNames
        {
            get => _shardNames ?? (_shardNames = new List<string>());
            set => _shardNames = value;
        }

        public GetMdbClickhouseClusterShardGroupArgs()
        {
        }
        public static new GetMdbClickhouseClusterShardGroupArgs Empty => new GetMdbClickhouseClusterShardGroupArgs();
    }
}
