// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class LoadtestingAgentComputeInstanceBootDiskArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether the disk is auto-deleted when the instance is deleted. The default value is true.
        /// </summary>
        [Input("autoDelete")]
        public Input<bool>? AutoDelete { get; set; }

        /// <summary>
        /// This value can be used to reference the device under `/dev/disk/by-id/`.
        /// </summary>
        [Input("deviceName")]
        public Input<string>? DeviceName { get; set; }

        /// <summary>
        /// The ID of created disk.
        /// </summary>
        [Input("diskId")]
        public Input<string>? DiskId { get; set; }

        /// <summary>
        /// Parameters for creating a disk alongside the instance. The structure is documented below.
        /// </summary>
        [Input("initializeParams", required: true)]
        public Input<Inputs.LoadtestingAgentComputeInstanceBootDiskInitializeParamsArgs> InitializeParams { get; set; } = null!;

        public LoadtestingAgentComputeInstanceBootDiskArgs()
        {
        }
        public static new LoadtestingAgentComputeInstanceBootDiskArgs Empty => new LoadtestingAgentComputeInstanceBootDiskArgs();
    }
}
