// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class MdbClickhouseClusterFormatSchemaGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the format schema.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Type of the format schema.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        /// <summary>
        /// Format schema file URL. You can only use format schemas stored in Yandex Object Storage.
        /// </summary>
        [Input("uri", required: true)]
        public Input<string> Uri { get; set; } = null!;

        public MdbClickhouseClusterFormatSchemaGetArgs()
        {
        }
        public static new MdbClickhouseClusterFormatSchemaGetArgs Empty => new MdbClickhouseClusterFormatSchemaGetArgs();
    }
}
