// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class MdbClickhouseClusterClickhouseConfigKafkaTopicSettingsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Action to take when there is no initial offset in offset store or the desired offset is out of range: 'smallest','earliest' - automatically reset the offset to the smallest offset, 'largest','latest' - automatically reset the offset to the largest offset, 'error' - trigger an error (ERR__AUTO_OFFSET_RESET) which is retrieved by consuming messages and checking 'message-&gt;err'.
        /// </summary>
        [Input("autoOffsetReset")]
        public Input<string>? AutoOffsetReset { get; set; }

        /// <summary>
        /// A comma-separated list of debug contexts to enable.
        /// </summary>
        [Input("debug")]
        public Input<string>? Debug { get; set; }

        /// <summary>
        /// enable verification of SSL certificates.
        /// </summary>
        [Input("enableSslCertificateVerification")]
        public Input<bool>? EnableSslCertificateVerification { get; set; }

        /// <summary>
        /// Maximum allowed time between calls to consume messages (e.g., rd_kafka_consumer_poll()) for high-level consumers. If this interval is exceeded the consumer is considered failed and the group will rebalance in order to reassign the partitions to another consumer group member.
        /// </summary>
        [Input("maxPollIntervalMs")]
        public Input<int>? MaxPollIntervalMs { get; set; }

        /// <summary>
        /// SASL mechanism used in kafka authentication.
        /// </summary>
        [Input("saslMechanism")]
        public Input<string>? SaslMechanism { get; set; }

        [Input("saslPassword")]
        private Input<string>? _saslPassword;

        /// <summary>
        /// User password on kafka server.
        /// </summary>
        public Input<string>? SaslPassword
        {
            get => _saslPassword;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _saslPassword = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Username on kafka server.
        /// </summary>
        [Input("saslUsername")]
        public Input<string>? SaslUsername { get; set; }

        /// <summary>
        /// Security protocol used to connect to kafka server.
        /// </summary>
        [Input("securityProtocol")]
        public Input<string>? SecurityProtocol { get; set; }

        /// <summary>
        /// Client group session and failure detection timeout. The consumer sends periodic heartbeats (heartbeat.interval.ms) to indicate its liveness to the broker. If no hearts are received by the broker for a group member within the session timeout, the broker will remove the consumer from the group and trigger a rebalance.
        /// </summary>
        [Input("sessionTimeoutMs")]
        public Input<int>? SessionTimeoutMs { get; set; }

        public MdbClickhouseClusterClickhouseConfigKafkaTopicSettingsArgs()
        {
        }
        public static new MdbClickhouseClusterClickhouseConfigKafkaTopicSettingsArgs Empty => new MdbClickhouseClusterClickhouseConfigKafkaTopicSettingsArgs();
    }
}
