// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class SmartcaptchaCaptchaSecurityRuleConditionUriGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("path")]
        public Input<Inputs.SmartcaptchaCaptchaSecurityRuleConditionUriPathGetArgs>? Path { get; set; }

        [Input("queries")]
        private InputList<Inputs.SmartcaptchaCaptchaSecurityRuleConditionUriQueryGetArgs>? _queries;
        public InputList<Inputs.SmartcaptchaCaptchaSecurityRuleConditionUriQueryGetArgs> Queries
        {
            get => _queries ?? (_queries = new InputList<Inputs.SmartcaptchaCaptchaSecurityRuleConditionUriQueryGetArgs>());
            set => _queries = value;
        }

        public SmartcaptchaCaptchaSecurityRuleConditionUriGetArgs()
        {
        }
        public static new SmartcaptchaCaptchaSecurityRuleConditionUriGetArgs Empty => new SmartcaptchaCaptchaSecurityRuleConditionUriGetArgs();
    }
}
