// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class SmartcaptchaCaptchaOverrideVariantGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("challengeType")]
        public Input<string>? ChallengeType { get; set; }

        [Input("complexity")]
        public Input<string>? Complexity { get; set; }

        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("preCheckType")]
        public Input<string>? PreCheckType { get; set; }

        [Input("uuid")]
        public Input<string>? Uuid { get; set; }

        public SmartcaptchaCaptchaOverrideVariantGetArgs()
        {
        }
        public static new SmartcaptchaCaptchaOverrideVariantGetArgs Empty => new SmartcaptchaCaptchaOverrideVariantGetArgs();
    }
}
