// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class SwsSecurityProfileSecurityRuleRuleConditionGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("action")]
        public Input<string>? Action { get; set; }

        [Input("condition")]
        public Input<Inputs.SwsSecurityProfileSecurityRuleRuleConditionConditionGetArgs>? Condition { get; set; }

        public SwsSecurityProfileSecurityRuleRuleConditionGetArgs()
        {
        }
        public static new SwsSecurityProfileSecurityRuleRuleConditionGetArgs Empty => new SwsSecurityProfileSecurityRuleRuleConditionGetArgs();
    }
}
