// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class SwsSecurityProfileSecurityRuleRuleConditionConditionGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("authority")]
        public Input<Inputs.SwsSecurityProfileSecurityRuleRuleConditionConditionAuthorityGetArgs>? Authority { get; set; }

        [Input("headers")]
        private InputList<Inputs.SwsSecurityProfileSecurityRuleRuleConditionConditionHeaderGetArgs>? _headers;
        public InputList<Inputs.SwsSecurityProfileSecurityRuleRuleConditionConditionHeaderGetArgs> Headers
        {
            get => _headers ?? (_headers = new InputList<Inputs.SwsSecurityProfileSecurityRuleRuleConditionConditionHeaderGetArgs>());
            set => _headers = value;
        }

        [Input("httpMethod")]
        public Input<Inputs.SwsSecurityProfileSecurityRuleRuleConditionConditionHttpMethodGetArgs>? HttpMethod { get; set; }

        [Input("requestUri")]
        public Input<Inputs.SwsSecurityProfileSecurityRuleRuleConditionConditionRequestUriGetArgs>? RequestUri { get; set; }

        [Input("sourceIp")]
        public Input<Inputs.SwsSecurityProfileSecurityRuleRuleConditionConditionSourceIpGetArgs>? SourceIp { get; set; }

        public SwsSecurityProfileSecurityRuleRuleConditionConditionGetArgs()
        {
        }
        public static new SwsSecurityProfileSecurityRuleRuleConditionConditionGetArgs Empty => new SwsSecurityProfileSecurityRuleRuleConditionConditionGetArgs();
    }
}
