// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class YdbTableTtlGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Column name for TTL
        /// </summary>
        [Input("columnName", required: true)]
        public Input<string> ColumnName { get; set; } = null!;

        /// <summary>
        /// Interval in the ISO 8601 format
        /// </summary>
        [Input("expireInterval", required: true)]
        public Input<string> ExpireInterval { get; set; } = null!;

        [Input("unit")]
        public Input<string>? Unit { get; set; }

        public YdbTableTtlGetArgs()
        {
        }
        public static new YdbTableTtlGetArgs Empty => new YdbTableTtlGetArgs();
    }
}
