// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getMdbElasticsearchCluster(args?: GetMdbElasticsearchClusterArgs, opts?: pulumi.InvokeOptions): Promise<GetMdbElasticsearchClusterResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("yandex:index/getMdbElasticsearchCluster:getMdbElasticsearchCluster", {
        "clusterId": args.clusterId,
        "deletionProtection": args.deletionProtection,
        "description": args.description,
        "folderId": args.folderId,
        "labels": args.labels,
        "name": args.name,
        "securityGroupIds": args.securityGroupIds,
        "serviceAccountId": args.serviceAccountId,
    }, opts);
}

/**
 * A collection of arguments for invoking getMdbElasticsearchCluster.
 */
export interface GetMdbElasticsearchClusterArgs {
    clusterId?: string;
    deletionProtection?: boolean;
    description?: string;
    folderId?: string;
    labels?: {[key: string]: string};
    name?: string;
    securityGroupIds?: string[];
    serviceAccountId?: string;
}

/**
 * A collection of values returned by getMdbElasticsearchCluster.
 */
export interface GetMdbElasticsearchClusterResult {
    readonly clusterId: string;
    readonly configs: outputs.GetMdbElasticsearchClusterConfig[];
    readonly createdAt: string;
    readonly deletionProtection: boolean;
    readonly description: string;
    readonly environment: string;
    readonly folderId: string;
    readonly health: string;
    readonly hosts: outputs.GetMdbElasticsearchClusterHost[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly labels: {[key: string]: string};
    readonly maintenanceWindows: outputs.GetMdbElasticsearchClusterMaintenanceWindow[];
    readonly name: string;
    readonly networkId: string;
    readonly securityGroupIds: string[];
    readonly serviceAccountId: string;
    readonly status: string;
}
export function getMdbElasticsearchClusterOutput(args?: GetMdbElasticsearchClusterOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetMdbElasticsearchClusterResult> {
    return pulumi.output(args).apply((a: any) => getMdbElasticsearchCluster(a, opts))
}

/**
 * A collection of arguments for invoking getMdbElasticsearchCluster.
 */
export interface GetMdbElasticsearchClusterOutputArgs {
    clusterId?: pulumi.Input<string>;
    deletionProtection?: pulumi.Input<boolean>;
    description?: pulumi.Input<string>;
    folderId?: pulumi.Input<string>;
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    name?: pulumi.Input<string>;
    securityGroupIds?: pulumi.Input<pulumi.Input<string>[]>;
    serviceAccountId?: pulumi.Input<string>;
}
