// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getMdbMongodbCluster(args?: GetMdbMongodbClusterArgs, opts?: pulumi.InvokeOptions): Promise<GetMdbMongodbClusterResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("yandex:index/getMdbMongodbCluster:getMdbMongodbCluster", {
        "clusterConfig": args.clusterConfig,
        "clusterId": args.clusterId,
        "createdAt": args.createdAt,
        "databases": args.databases,
        "deletionProtection": args.deletionProtection,
        "description": args.description,
        "diskSizeAutoscalingMongocfg": args.diskSizeAutoscalingMongocfg,
        "diskSizeAutoscalingMongod": args.diskSizeAutoscalingMongod,
        "diskSizeAutoscalingMongoinfra": args.diskSizeAutoscalingMongoinfra,
        "diskSizeAutoscalingMongos": args.diskSizeAutoscalingMongos,
        "environment": args.environment,
        "folderId": args.folderId,
        "health": args.health,
        "hosts": args.hosts,
        "labels": args.labels,
        "maintenanceWindow": args.maintenanceWindow,
        "name": args.name,
        "networkId": args.networkId,
        "resources": args.resources,
        "resourcesMongocfg": args.resourcesMongocfg,
        "resourcesMongod": args.resourcesMongod,
        "resourcesMongoinfra": args.resourcesMongoinfra,
        "resourcesMongos": args.resourcesMongos,
        "restore": args.restore,
        "securityGroupIds": args.securityGroupIds,
        "sharded": args.sharded,
        "status": args.status,
        "users": args.users,
    }, opts);
}

/**
 * A collection of arguments for invoking getMdbMongodbCluster.
 */
export interface GetMdbMongodbClusterArgs {
    clusterConfig?: inputs.GetMdbMongodbClusterClusterConfig;
    clusterId?: string;
    createdAt?: string;
    /**
     * @deprecated to manage databases, please switch to using a separate resource type yandex_mdb_mongodb_database
     */
    databases?: inputs.GetMdbMongodbClusterDatabase[];
    deletionProtection?: boolean;
    description?: string;
    diskSizeAutoscalingMongocfg?: inputs.GetMdbMongodbClusterDiskSizeAutoscalingMongocfg;
    diskSizeAutoscalingMongod?: inputs.GetMdbMongodbClusterDiskSizeAutoscalingMongod;
    diskSizeAutoscalingMongoinfra?: inputs.GetMdbMongodbClusterDiskSizeAutoscalingMongoinfra;
    diskSizeAutoscalingMongos?: inputs.GetMdbMongodbClusterDiskSizeAutoscalingMongos;
    environment?: string;
    folderId?: string;
    health?: string;
    hosts?: inputs.GetMdbMongodbClusterHost[];
    labels?: {[key: string]: string};
    maintenanceWindow?: inputs.GetMdbMongodbClusterMaintenanceWindow;
    name?: string;
    networkId?: string;
    /**
     * @deprecated to manage `resources`s, please switch to using a separate resource type `resources_mongo*`
     */
    resources?: inputs.GetMdbMongodbClusterResources;
    resourcesMongocfg?: inputs.GetMdbMongodbClusterResourcesMongocfg;
    resourcesMongod?: inputs.GetMdbMongodbClusterResourcesMongod;
    resourcesMongoinfra?: inputs.GetMdbMongodbClusterResourcesMongoinfra;
    resourcesMongos?: inputs.GetMdbMongodbClusterResourcesMongos;
    restore?: inputs.GetMdbMongodbClusterRestore;
    securityGroupIds?: string[];
    sharded?: boolean;
    status?: string;
    /**
     * @deprecated to manage users, please switch to using a separate resource type yandex_mdb_mongodb_user
     */
    users?: inputs.GetMdbMongodbClusterUser[];
}

/**
 * A collection of values returned by getMdbMongodbCluster.
 */
export interface GetMdbMongodbClusterResult {
    readonly clusterConfig?: outputs.GetMdbMongodbClusterClusterConfig;
    readonly clusterId: string;
    readonly createdAt: string;
    /**
     * @deprecated to manage databases, please switch to using a separate resource type yandex_mdb_mongodb_database
     */
    readonly databases: outputs.GetMdbMongodbClusterDatabase[];
    readonly deletionProtection: boolean;
    readonly description?: string;
    readonly diskSizeAutoscalingMongocfg: outputs.GetMdbMongodbClusterDiskSizeAutoscalingMongocfg;
    readonly diskSizeAutoscalingMongod: outputs.GetMdbMongodbClusterDiskSizeAutoscalingMongod;
    readonly diskSizeAutoscalingMongoinfra: outputs.GetMdbMongodbClusterDiskSizeAutoscalingMongoinfra;
    readonly diskSizeAutoscalingMongos: outputs.GetMdbMongodbClusterDiskSizeAutoscalingMongos;
    readonly environment?: string;
    readonly folderId: string;
    readonly health: string;
    readonly hosts?: outputs.GetMdbMongodbClusterHost[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly labels: {[key: string]: string};
    readonly maintenanceWindow: outputs.GetMdbMongodbClusterMaintenanceWindow;
    readonly name?: string;
    readonly networkId?: string;
    /**
     * @deprecated to manage `resources`s, please switch to using a separate resource type `resources_mongo*`
     */
    readonly resources?: outputs.GetMdbMongodbClusterResources;
    readonly resourcesMongocfg?: outputs.GetMdbMongodbClusterResourcesMongocfg;
    readonly resourcesMongod?: outputs.GetMdbMongodbClusterResourcesMongod;
    readonly resourcesMongoinfra?: outputs.GetMdbMongodbClusterResourcesMongoinfra;
    readonly resourcesMongos?: outputs.GetMdbMongodbClusterResourcesMongos;
    readonly restore?: outputs.GetMdbMongodbClusterRestore;
    readonly securityGroupIds?: string[];
    readonly sharded: boolean;
    readonly status: string;
    /**
     * @deprecated to manage users, please switch to using a separate resource type yandex_mdb_mongodb_user
     */
    readonly users: outputs.GetMdbMongodbClusterUser[];
}
export function getMdbMongodbClusterOutput(args?: GetMdbMongodbClusterOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetMdbMongodbClusterResult> {
    return pulumi.output(args).apply((a: any) => getMdbMongodbCluster(a, opts))
}

/**
 * A collection of arguments for invoking getMdbMongodbCluster.
 */
export interface GetMdbMongodbClusterOutputArgs {
    clusterConfig?: pulumi.Input<inputs.GetMdbMongodbClusterClusterConfigArgs>;
    clusterId?: pulumi.Input<string>;
    createdAt?: pulumi.Input<string>;
    /**
     * @deprecated to manage databases, please switch to using a separate resource type yandex_mdb_mongodb_database
     */
    databases?: pulumi.Input<pulumi.Input<inputs.GetMdbMongodbClusterDatabaseArgs>[]>;
    deletionProtection?: pulumi.Input<boolean>;
    description?: pulumi.Input<string>;
    diskSizeAutoscalingMongocfg?: pulumi.Input<inputs.GetMdbMongodbClusterDiskSizeAutoscalingMongocfgArgs>;
    diskSizeAutoscalingMongod?: pulumi.Input<inputs.GetMdbMongodbClusterDiskSizeAutoscalingMongodArgs>;
    diskSizeAutoscalingMongoinfra?: pulumi.Input<inputs.GetMdbMongodbClusterDiskSizeAutoscalingMongoinfraArgs>;
    diskSizeAutoscalingMongos?: pulumi.Input<inputs.GetMdbMongodbClusterDiskSizeAutoscalingMongosArgs>;
    environment?: pulumi.Input<string>;
    folderId?: pulumi.Input<string>;
    health?: pulumi.Input<string>;
    hosts?: pulumi.Input<pulumi.Input<inputs.GetMdbMongodbClusterHostArgs>[]>;
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    maintenanceWindow?: pulumi.Input<inputs.GetMdbMongodbClusterMaintenanceWindowArgs>;
    name?: pulumi.Input<string>;
    networkId?: pulumi.Input<string>;
    /**
     * @deprecated to manage `resources`s, please switch to using a separate resource type `resources_mongo*`
     */
    resources?: pulumi.Input<inputs.GetMdbMongodbClusterResourcesArgs>;
    resourcesMongocfg?: pulumi.Input<inputs.GetMdbMongodbClusterResourcesMongocfgArgs>;
    resourcesMongod?: pulumi.Input<inputs.GetMdbMongodbClusterResourcesMongodArgs>;
    resourcesMongoinfra?: pulumi.Input<inputs.GetMdbMongodbClusterResourcesMongoinfraArgs>;
    resourcesMongos?: pulumi.Input<inputs.GetMdbMongodbClusterResourcesMongosArgs>;
    restore?: pulumi.Input<inputs.GetMdbMongodbClusterRestoreArgs>;
    securityGroupIds?: pulumi.Input<pulumi.Input<string>[]>;
    sharded?: pulumi.Input<boolean>;
    status?: pulumi.Input<string>;
    /**
     * @deprecated to manage users, please switch to using a separate resource type yandex_mdb_mongodb_user
     */
    users?: pulumi.Input<pulumi.Input<inputs.GetMdbMongodbClusterUserArgs>[]>;
}
