// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getVpcSecurityGroup(args?: GetVpcSecurityGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetVpcSecurityGroupResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("yandex:index/getVpcSecurityGroup:getVpcSecurityGroup", {
        "folderId": args.folderId,
        "name": args.name,
        "securityGroupId": args.securityGroupId,
    }, opts);
}

/**
 * A collection of arguments for invoking getVpcSecurityGroup.
 */
export interface GetVpcSecurityGroupArgs {
    folderId?: string;
    name?: string;
    securityGroupId?: string;
}

/**
 * A collection of values returned by getVpcSecurityGroup.
 */
export interface GetVpcSecurityGroupResult {
    readonly createdAt: string;
    readonly description: string;
    readonly egresses: outputs.GetVpcSecurityGroupEgress[];
    readonly folderId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly ingresses: outputs.GetVpcSecurityGroupIngress[];
    readonly labels: {[key: string]: string};
    readonly name: string;
    readonly networkId: string;
    readonly securityGroupId: string;
    readonly status: string;
}
export function getVpcSecurityGroupOutput(args?: GetVpcSecurityGroupOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetVpcSecurityGroupResult> {
    return pulumi.output(args).apply((a: any) => getVpcSecurityGroup(a, opts))
}

/**
 * A collection of arguments for invoking getVpcSecurityGroup.
 */
export interface GetVpcSecurityGroupOutputArgs {
    folderId?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    securityGroupId?: pulumi.Input<string>;
}
