// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * A Load Testing Agent resource. For more information, see
 * [the official documentation](https://cloud.yandex.com/en/docs/load-testing/concepts/agent).
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as yandex from "@pulumi/yandex";
 *
 * const my_agent = new yandex.LoadtestingAgent("my-agent", {
 *     computeInstance: {
 *         bootDisk: {
 *             autoDelete: true,
 *             initializeParams: {
 *                 size: 15,
 *             },
 *         },
 *         networkInterfaces: [{
 *             subnetId: yandex_vpc_subnet["my-subnet-a"].id,
 *         }],
 *         resources: {
 *             cores: 2,
 *             memory: 4,
 *         },
 *         serviceAccountId: yandex_iam_service_account.test_account.id,
 *         zoneId: "ru-central1-b",
 *     },
 *     description: "2 core 4 GB RAM agent",
 *     folderId: data.yandex_resourcemanager_folder.test_folder.id,
 *     labels: {
 *         jmeter: "5",
 *     },
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 */
export class LoadtestingAgent extends pulumi.CustomResource {
    /**
     * Get an existing LoadtestingAgent resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: LoadtestingAgentState, opts?: pulumi.CustomResourceOptions): LoadtestingAgent {
        return new LoadtestingAgent(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'yandex:index/loadtestingAgent:LoadtestingAgent';

    /**
     * Returns true if the given object is an instance of LoadtestingAgent.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is LoadtestingAgent {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === LoadtestingAgent.__pulumiType;
    }

    /**
     * The template for creating new compute instance running load testing agent. The structure is documented below.
     */
    public readonly computeInstance!: pulumi.Output<outputs.LoadtestingAgentComputeInstance>;
    public /*out*/ readonly computeInstanceId!: pulumi.Output<string>;
    /**
     * A description of the load testing agent.
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * The ID of the folder that the resources belong to.
     */
    public readonly folderId!: pulumi.Output<string>;
    /**
     * A set of key/value label pairs to assign to the agent.
     */
    public readonly labels!: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * The name of the load testing agent. Must be unique within folder.
     */
    public readonly name!: pulumi.Output<string>;

    /**
     * Create a LoadtestingAgent resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: LoadtestingAgentArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: LoadtestingAgentArgs | LoadtestingAgentState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as LoadtestingAgentState | undefined;
            resourceInputs["computeInstance"] = state ? state.computeInstance : undefined;
            resourceInputs["computeInstanceId"] = state ? state.computeInstanceId : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["folderId"] = state ? state.folderId : undefined;
            resourceInputs["labels"] = state ? state.labels : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
        } else {
            const args = argsOrState as LoadtestingAgentArgs | undefined;
            if ((!args || args.computeInstance === undefined) && !opts.urn) {
                throw new Error("Missing required property 'computeInstance'");
            }
            resourceInputs["computeInstance"] = args ? args.computeInstance : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["folderId"] = args ? args.folderId : undefined;
            resourceInputs["labels"] = args ? args.labels : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["computeInstanceId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(LoadtestingAgent.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering LoadtestingAgent resources.
 */
export interface LoadtestingAgentState {
    /**
     * The template for creating new compute instance running load testing agent. The structure is documented below.
     */
    computeInstance?: pulumi.Input<inputs.LoadtestingAgentComputeInstance>;
    computeInstanceId?: pulumi.Input<string>;
    /**
     * A description of the load testing agent.
     */
    description?: pulumi.Input<string>;
    /**
     * The ID of the folder that the resources belong to.
     */
    folderId?: pulumi.Input<string>;
    /**
     * A set of key/value label pairs to assign to the agent.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The name of the load testing agent. Must be unique within folder.
     */
    name?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a LoadtestingAgent resource.
 */
export interface LoadtestingAgentArgs {
    /**
     * The template for creating new compute instance running load testing agent. The structure is documented below.
     */
    computeInstance: pulumi.Input<inputs.LoadtestingAgentComputeInstance>;
    /**
     * A description of the load testing agent.
     */
    description?: pulumi.Input<string>;
    /**
     * The ID of the folder that the resources belong to.
     */
    folderId?: pulumi.Input<string>;
    /**
     * A set of key/value label pairs to assign to the agent.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The name of the load testing agent. Must be unique within folder.
     */
    name?: pulumi.Input<string>;
}
