// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class YdbTableChangefeed extends pulumi.CustomResource {
    /**
     * Get an existing YdbTableChangefeed resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: YdbTableChangefeedState, opts?: pulumi.CustomResourceOptions): YdbTableChangefeed {
        return new YdbTableChangefeed(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'yandex:index/ydbTableChangefeed:YdbTableChangefeed';

    /**
     * Returns true if the given object is an instance of YdbTableChangefeed.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is YdbTableChangefeed {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === YdbTableChangefeed.__pulumiType;
    }

    public readonly connectionString!: pulumi.Output<string>;
    public readonly consumers!: pulumi.Output<outputs.YdbTableChangefeedConsumer[]>;
    public readonly format!: pulumi.Output<string>;
    public readonly mode!: pulumi.Output<string>;
    public readonly name!: pulumi.Output<string>;
    public readonly retentionPeriod!: pulumi.Output<string | undefined>;
    public readonly tableId!: pulumi.Output<string>;
    public readonly tablePath!: pulumi.Output<string>;
    public readonly virtualTimestamps!: pulumi.Output<boolean | undefined>;

    /**
     * Create a YdbTableChangefeed resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: YdbTableChangefeedArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: YdbTableChangefeedArgs | YdbTableChangefeedState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as YdbTableChangefeedState | undefined;
            resourceInputs["connectionString"] = state ? state.connectionString : undefined;
            resourceInputs["consumers"] = state ? state.consumers : undefined;
            resourceInputs["format"] = state ? state.format : undefined;
            resourceInputs["mode"] = state ? state.mode : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["retentionPeriod"] = state ? state.retentionPeriod : undefined;
            resourceInputs["tableId"] = state ? state.tableId : undefined;
            resourceInputs["tablePath"] = state ? state.tablePath : undefined;
            resourceInputs["virtualTimestamps"] = state ? state.virtualTimestamps : undefined;
        } else {
            const args = argsOrState as YdbTableChangefeedArgs | undefined;
            if ((!args || args.format === undefined) && !opts.urn) {
                throw new Error("Missing required property 'format'");
            }
            if ((!args || args.mode === undefined) && !opts.urn) {
                throw new Error("Missing required property 'mode'");
            }
            resourceInputs["connectionString"] = args ? args.connectionString : undefined;
            resourceInputs["consumers"] = args ? args.consumers : undefined;
            resourceInputs["format"] = args ? args.format : undefined;
            resourceInputs["mode"] = args ? args.mode : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["retentionPeriod"] = args ? args.retentionPeriod : undefined;
            resourceInputs["tableId"] = args ? args.tableId : undefined;
            resourceInputs["tablePath"] = args ? args.tablePath : undefined;
            resourceInputs["virtualTimestamps"] = args ? args.virtualTimestamps : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(YdbTableChangefeed.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering YdbTableChangefeed resources.
 */
export interface YdbTableChangefeedState {
    connectionString?: pulumi.Input<string>;
    consumers?: pulumi.Input<pulumi.Input<inputs.YdbTableChangefeedConsumer>[]>;
    format?: pulumi.Input<string>;
    mode?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    retentionPeriod?: pulumi.Input<string>;
    tableId?: pulumi.Input<string>;
    tablePath?: pulumi.Input<string>;
    virtualTimestamps?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a YdbTableChangefeed resource.
 */
export interface YdbTableChangefeedArgs {
    connectionString?: pulumi.Input<string>;
    consumers?: pulumi.Input<pulumi.Input<inputs.YdbTableChangefeedConsumer>[]>;
    format: pulumi.Input<string>;
    mode: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    retentionPeriod?: pulumi.Input<string>;
    tableId?: pulumi.Input<string>;
    tablePath?: pulumi.Input<string>;
    virtualTimestamps?: pulumi.Input<boolean>;
}
